### ISSUE TITLE
Failed to install/rebuild Hydrogen@2.14.7

### ISSUE THREAD

**Issue by WhyBeU** [nteract/hydrogen#2077] opened 2021-04-14 05:14 UTC
### Prerequisites

- [ Y] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
- [Y ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hi, thanks for the awesome package, I have been using for almost 3 years now. 
While starting the day, Got an issue where the package would not run and issue an error (upon starting the kernel) which prompted to rebuild the package (Hydrogen). The package failed to rebuild. I went on to uninstall and reinstall the package.
Upon installation I still encountered the following error. 
Thanks for the help!

> zeromq@5.2.0 install C:\Users\z5189526\AppData\Local\Temp\apm-install-dir-2021314-14752-z8u63i.0335b\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install No prebuilt binaries found (target=9.4.4 runtime=electron arch=x64 libc= platform=win32)

Downloading libzmq for Windows
Download finished

C:\Users\z5189526\AppData\Local\Temp\apm-install-dir-2021314-14752-z8u63i.0335b\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\z5189526\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\z5189526\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\z5189526\AppData\Local\Temp\apm-install-dir-2021314-14752-z8u63i.0335b\node_modules\Hydrogen\node_modules\zeromq\build\zmq.vcxproj]

npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\z5189526\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\z5189526\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\z5189526\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\z5189526\AppData\Local\Temp\apm-install-dir-2021314-14752-z8u63i.0335b\node_modules\Hydrogen\node_modules\zeromq
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\z5189526\AppData\Local\Temp\apm-install-dir-2021314-14752-z8u63i.0335b\package.json'
npm WARN apm-install-dir-2021314-14752-z8u63i.0335b No description
npm WARN apm-install-dir-2021314-14752-z8u63i.0335b No repository field.
npm WARN apm-install-dir-2021314-14752-z8u63i.0335b No README data
npm WARN apm-install-dir-2021314-14752-z8u63i.0335b No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\z5189526\.atom\.apm\_logs\2021-04-14T05_05_20_665Z-debug.log

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.6.6
git 2.30.0.windows.2
visual studio

OS version:
Windows Version	10.0.19042 Build 19042

Hydrogen version:
2.14.7

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?

- [ N] hydrogen-python
- [ N] Hydrogen Launcher
- [ N] Data Explorer

**Comment by WhyBeU** [comment] 2021-04-14 05:15
[2021-04-14T05_13_27_613Z-debug.log](https://github.com/nteract/hydrogen/files/6308309/2021-04-14T05_13_27_613Z-debug.log)

**Comment by aminya** [comment] 2021-04-14 05:56
Duplicate of #2034

**Closed by aminya** 2021-04-14 05:56 UTC
Labels: bug :bug:

**Comment by aminya** [comment] 2021-04-15 08:53
Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉
