### ISSUE TITLE
Atom Hydrogen Freezes

### ISSUE THREAD

**Issue by optionsraghu** [nteract/hydrogen#1680] opened 2019-06-26 14:01 UTC
Dear Atomists!
After I updated to  2.10.0 Hydrogen , the CURSOR on the editor freezes whenever an output window is closed or whenever I come back from another window into atom. I tried re-installing Hydrogen, tried re-installing atom itself but it persists. 
Any advice please?
Thanks

**Comment by wadethestealth** [comment] 2019-06-26 14:26
You could try downgrading back to 2.9 and letting us know if the freezing still happens, in which case it would be something else causing it.

**Comment by optionsraghu** [comment] 2019-06-26 16:02
Brilliant! Thanks Wade. That did the trick. Appreciate your help.
But that means there is a bug on 2.10.0.

**Comment by wadethestealth** [comment] 2019-06-26 16:09
I prefer not to close the issue, and could you gives us some simple steps to reproduce what happened

**Comment by optionsraghu** [comment] 2019-06-26 16:16
well as i mentioned, I just upgraded to a newer version (2.10.0) and whenever I ran a line of code or a bunch of it, and when the output window was closed manually by clicking on the cross, the cursor on the window just froze and wouldn't budge. the same issue was observed when i had to toggle between different windows (chrome, firefox, atom etc). one way i was able to adjust to this was by clicking on the mouse button once and the cursor would 'wake up'. as per your suggestion i have gone back to the older ver (2.9.0) and it works like a peach. thank you.

**Comment by shr00mie** [comment] 2019-06-26 17:42
i can confirm this behavior as well in 2.10.0.

under 2.10.0, to get the cursor to unstick, you'd have to do a combination of either using arrow keys or clicking on another line with the mouse. behavior stopped after reverting to 2.9.0.

**Comment by BenRussert** [comment] 2019-06-26 23:02
https://github.com/nteract/hydrogen/blob/695adf9608a2d5987cba7a5f9765f0964222e1c9/lib/components/result-view/result-view.js#L149

@wadethestealth From messing around in devtools a bit I'm pretty sure [this line](https://github.com/nteract/hydrogen/blob/695adf9608a2d5987cba7a5f9765f0964222e1c9/lib/components/result-view/result-view.js#L149) causes the issue. I'm hoping there is a way to keep the selection behavior, but not set the tab index. I assume the tab index part is important though?

**Comment by wadethestealth** [comment] 2019-06-26 23:03
I don't understand how that causes a freeze, I think I tried removing it before, but I think it's necessary.

**Comment by wadethestealth** [comment] 2019-06-26 23:06
It may be because of the output pane being selectable too. May it should only have -1 when there is no output pane?

**Comment by wadethestealth** [comment] 2019-06-26 23:07
I am not too sure how tabIndex works behind the scenes though

**Comment by BenRussert** [comment] 2019-06-27 14:50
It's not exactly a "freeze", it just removes focus from the cursor/editor element and makes the root body the active element.

So basically the user has to click back to where they were.

**Comment by wadethestealth** [comment] 2019-06-27 14:56
Ok will take a look later and update this comment

**Comment by BenRussert** [comment] 2019-06-27 14:56
To reproduce, just run any code with multi-line (in editor) output. Then click the close box to destroy the output. Your cursor will visibly still be there, but focus changes unexpectedly from where you were.

For easy repro:

```python
from IPython.display import HTML

display(HTML("<h1>Multiple</h1>"))


```

**Comment by wadethestealth** [comment] 2019-06-27 17:41
@BenRussert I have working fix now. I am just trying to see if there is a better way to implement. I will open a PR soon.

**Closed** 2019-06-28 02:20 UTC
Labels: bug :bug:, work in progress :construction_worker_man:

**Comment by optionsraghu** [comment] 2019-06-28 22:01
so does it mean i can upgrade to 2.10.0 now? thanks.

**Comment by wadethestealth** [comment] 2019-06-28 22:22
2.10.2 @optionsraghu

**Comment by optionsraghu** [comment] 2019-07-02 19:18
Thanks @wadethestealth

**Comment by optionsraghu** [comment] 2019-07-02 19:20
@wadethestealth  I also have issues with atom freeze when I run some intensive time series models (such as Sarimax etc). Is this the forum to report it too? Thanks.

**Comment by wadethestealth** [comment] 2019-07-02 19:25
@optionsraghu No it does not, but it may be beneficial for you to look and measure your kernels performance to see what hangs. You could also view atom dev tools performance to see if hydrogen is causing the large delays. If you found out it's hydrogen, it would be nice if you could open up an issue show a screenshot of the performance with code to replicate
