### ISSUE TITLE
Spawns kernels when loading atom (?)

### ISSUE THREAD

**Issue by tpoisot** [nteract/hydrogen#108] opened 2015-09-14 15:48 UTC
I think (and it's really hard to reproduce) that when I reload atom, in dev mode, sometimes a julia thread spawns that take 100% CPU.

**Comment by willwhitney** [comment] 2015-09-14 17:05
This doesn't sound like a thing that would happen, but please let me know if you figure out anything more. Hydrogen should only be starting kernels when you first tell it to run some code. In fact, Hydrogen itself shouldn't be activated by Atom until you use `hydrogen:run` or its shortcut.

**Comment by tpoisot** [comment] 2015-09-14 18:49
Definitely happens when I start an atom session in `~`.

**Comment by willwhitney** [comment] 2015-09-15 15:59
Can you open the console in the Atom dev tools (View -> Developer) and see what Hydrogen is printing out? Hydrogen spits out a bunch of logs to make it easier to debug this sort of thing.

**Comment by terraqout** [comment] 2015-09-16 11:34
@tpoisot Don't you using language-julia or autocomplete julia? I had the same issue with them, but not with hydrogen - it doen't start kernel on atom restart.

You can check this by:
ps aux | grep hydrogen

**Comment by n-riesco** [comment] 2016-07-21 08:06
@tpoisot I'm closing this issue. Please, feel free to reopen if you still need help.

**Comment by tpoisot** [comment] 2016-07-21 11:50
that's fine -- I removed the package bc  the issue persisted, and use the notebook instead.

t

**Comment by n-riesco** [comment] 2016-09-15 08:55
Reopening because the issue persists.

**Comment by lgeiger** [comment] 2016-09-15 10:37
Oh really I just checked and can't reproduce this.

**Comment by n-riesco** [comment] 2016-09-15 10:47
@lgeiger Did you use the IJulia kernel?

**Comment by lgeiger** [comment] 2016-09-15 10:53
I should have read the issue more carefully. No, I only have python, root and ijavascript installed.

**Comment by BenRussert** [comment] 2017-03-25 00:49
@n-riesco have you experienced this lately? I know when i first tried out the uber-juno (and the packages it installs) I was having issues with it having conflicting keybindings with Hydrogen. 

uber-juno installs: tool-bar, latex-completions, language-julia, ink, julia-client

I disabled uber-juno packages early on because I thought it was spawning julia on startup, but have since tried and not seen the same issue.

**Comment by n-riesco** [comment] 2017-03-25 18:40
@BenRussert I've just tested IJulia v1.4.1 on Hydrogen v1.6.0 and the 100%-CPU spike is hardly noticeable.

---

A comment for IJulia users:

IJulia users should expect a little delay when running IJulia for the first time after installation (because the package has to be precompiled; Hydrogen now shows a notification when this happens). But this delay is a one time thing. It won't happen next time you run IJulia.

**Comment by willingc** [comment] 2017-03-25 19:23
@n-riesco You've given an excellent explanation. Thanks!

@lgeiger How do you feel about closing this issue as resolved?

**Comment by lgeiger** [comment] 2017-03-25 19:28
@n-riesco Thanks for the great explanation and testing!

I think we can close this as resolved 👍 

@tpoisot Feel free to reopen if you still have issues.

**Closed by lgeiger** 2017-03-25 19:28 UTC
Labels: bug
