### ISSUE TITLE
constant 10% CPU by Atom Helper after python kernel is launched on Mac OS

### ISSUE THREAD

**Issue by odp** [nteract/hydrogen#646] opened 2017-03-20 00:44 UTC
**Description:**

constant 10% cpu by Atom Helper. Attaching the profile sample of running process.  

**Steps to Reproduce:**
Open python code. Launch python kernel. 

**Versions:**

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Hydrogen: 1.6.0

**Logs:**
[Sample of Atom Helper.txt](https://github.com/nteract/hydrogen/files/853719/Sample.of.Atom.Helper.txt)

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

**Comment by lgeiger** [comment] 2017-03-20 20:13
I see the same behavior on my machine and observed it in `nteract` too which makes sense since we share the same tooling.

A increase in CPU usage is expected since we need to spawn a process which runs the desired kernel. Though I have no idea why it's so high.

Two possible bottlenecks would be the [zeromq](https://github.com/zeromq/zeromq.js) messaging or the [child_process](https://nodejs.org/api/child_process.html) we spawn from Node. I'm wondering if [detaching](https://nodejs.org/api/child_process.html#child_process_options_detached) it helps.

**Comment by n-riesco** [comment] 2017-03-28 17:43
I cannot reproduce this issue (but I'm using an old version: v1.6.0).

@lgeiger There is something that may introduce a constant load and that is unnecessary. Could you check if removing [these lines](https://github.com/nteract/hydrogen/blob/246efea6c2b6c6c04f09b8afd373857d20964e4d/lib/zmq-kernel.js#L109-L116) has any effect on CPU usage?

**Comment by lgeiger** [comment] 2017-03-28 23:38
@n-riesco I'll check tomorrow 👍 

Though I don't think this is a problem with Hydrogen itself.

One thing to note is that zeromq.js for Mac and Windows ships with libzmq 4.2.0, the Linux version of uses 4.1.6 (since we weren't able to bundle 4.2.0). This may be a thing to look into.

@rgbkrk I haven't followed the zeromq mailing list, do you know of any reports about higher CPU usage in version 4.2.x?

**Comment by rgbkrk** [comment] 2017-03-28 23:53
Nothing on the list. Any ideas @taotetek?

**Comment by n-riesco** [comment] 2017-03-29 08:32
> Though I don't think this is a problem with Hydrogen itself.

I don't follow the reasoning above. Aren't those lines part of Hydrogen?

**Comment by lgeiger** [comment] 2017-03-29 12:37
>Though I don't think this is a problem with Hydrogen itself.

Never mind, I think we mean the same thing 😄 . I was trying to say, we probably _call_ something that introduces a constant load.

**Comment by lgeiger** [comment] 2017-03-29 12:59
@n-riesco Thanks a lot for the great idea.

It was a bit tricky to reproduce this reliably since every interaction with Atom (even scroll or mouse movement) resulted in a big increase in CPU usage.

## The testing method
1. Close all unnecessary programs
2. Unfocus Atom and wait until CPU load stabilizes
3. Start two kernels to make the effect more prominent
4. Unfocus Atom to only measure background tasks and reduce CPU load by the render process
5. Wait until CPU load stabilizes

## Results
### master:
11% CPU usage by Atom Helper
https://youtu.be/eqi9fJcuLPk

### Without [zeromq monitoring](https://github.com/nteract/hydrogen/blob/246efea6c2b6c6c04f09b8afd373857d20964e4d/lib/zmq-kernel.js#L109-L116):

0.2% CPU usage by Atom Helper 🎉 🚀 
https://youtu.be/zJuuHDs7gts

## Conclusion

@n-riesco @rgbkrk Do we really need monitoring or can we simply remove it.
I don't know much about zeromq other than how to get it installed properly 😉

**Comment by n-riesco** [comment] 2017-03-29 13:36
I was planning to submit a PR similar to [this commit](https://github.com/n-riesco/jp-kernel/pull/4/commits/ac8ef4cbdf0dce88dc889aedfed9c993867bd0e1) (since it fixes the startup issues in IJavascript #591). But I wanted to experiment with it a little bit more.

@lgeiger Since this is causing such a CPU usage, I could submit the PR now and update it later on if necessary.

---

The idea behind the PR is that we monitor the `hb`, `shell`, `control` and `io` sockets until we get a connect message (i.e. we call `socket.unmonitor()` when we get a `connect` event). Note that I've excluded the `stdin` socket because it may never be used.

**Comment by rgbkrk** [comment] 2017-03-29 13:39
I like the approach of unmonitoring after a connect message. I don't know much about monitoring with zeromq. /cc @minrk

**Comment by minrk** [comment] 2017-03-29 14:05
If you are only using it for the first connect event, disabling monitoring after you get it is a good idea. I'd encourage not monitoring at all, though. I think it's a bit of an anti-pattern in zeromq. zmq sockets can be used before connections are established, so there isn't much benefit to being notified that the connection event occurred, other than debugging.

**Comment by n-riesco** [comment] 2017-03-29 14:32
@minrk monitoring here is used as a workaround. Issues like #88 and more recently #591 suggest there is a bug in the zeromq binding for Node.js, that causes a socket to stop notifying when a new message arrives. Unfortunately, there are multiple ways to trigger this issue, some [reproducible ways](https://github.com/JustinTulloss/zeromq.node/issues/558), some not (#591, #88, ...).

In this case monitoring seems to workaround the connection issues in #591.

**Comment by lgeiger** [comment] 2017-03-29 15:57
@n-riesco Are you sure #88 is still a issue with since we're using [`zeromq.js`](https://github.com/zeromq/zeromq.js) with libzmq 4 now?

By the way it looks like https://github.com/JustinTulloss/zeromq.node/issues/558 is already fixed though I'm not sure if the fix is included in `zeromq.js`.

**Closed** 2017-03-31 19:35 UTC
Labels: help wanted
