### ISSUE TITLE
2.2.0 Update fails

### ISSUE THREAD

**Issue by black-snow** [nteract/hydrogen#1151] opened 2017-12-20 16:39 UTC
**Description:**

Update fails.

**Steps to Reproduce:**

1. Have a version < 2.2.0
2. Try updating to 2.2.0 (via atom ui)

**Versions:**

Wind10, fall creators
Atom 1.23.1

**Logs:**

```
Installing “Hydrogen@2.2.0” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\xxx\.atom\packages\Hydrogen\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\m02ph\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\xxx\AppData\Local\atom\app-1.23.1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\xxx\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\m02ph\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by black-snow** [comment] 2017-12-20 16:42
`apm install hydrogen` worked ...

**Comment by lgeiger** [comment] 2017-12-20 17:02
Closing as a duplicate of #1150

**Closed by lgeiger** 2017-12-20 17:02 UTC
Labels: duplicate, install
