### ISSUE TITLE
Multiline output is covered by code

### ISSUE THREAD

**Issue by botcs** [nteract/hydrogen#907] opened 2017-07-06 11:12 UTC
**Description:**
When the kernel is running and a multi line output is expected then it appears to occupy one line below but the other parts are invisible/covered
[Description of the issue]

**Steps to Reproduce:**
for example when I run this

```python
import pygame
import numpy as np
```

I get an image like  this:
https://pasteboard.co/GzFD9wt.png

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
OS: Ubuntu 16.04 - Hydrogen: 1.19.0 - Atom: 1.19.0-beta2
You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Comment by lgeiger** [comment] 2017-07-06 11:17
Closing as a duplicate of #898

This will be fixed in the upcoming Atom: 1.19.0-beta3 release. Until that you can use the external output area with "Hydrogen: Toggle Output Area".

**Closed by lgeiger** 2017-07-06 11:17 UTC
