### ISSUE TITLE
Please port to Vs Code or any other IDE

### ISSUE THREAD

**Issue by O5-3TheKid** [nteract/hydrogen#2159] opened 2022-11-13 17:12 UTC
As you know atom is being sunset and lighttable is still dead. There is nothing like hydrogen for any other IDE I can find. Please don't let this resource die.

**Comment by aminya** [comment] 2022-11-14 04:46
Duplicate of https://github.com/nteract/hydrogen/issues/2155

**Closed** 2022-11-14 04:47 UTC
Labels: enhancement :star2:
