### ISSUE TITLE
Hydrogen Atom output window issues

### ISSUE THREAD

**Issue by srk-srinivasan** [nteract/hydrogen#981] opened 2017-09-07 13:24 UTC
I have Hygdrogen installed for my Atom editor. It was working fine till yesterday. When I run using shift+enter, the output window displays the result however when I close the output window the window closes leaving behind huge space. After that all my coding lines are disrupted and I cant further code. Any help is highly appreciated. 
Screenshot 1: is normal open output window.
Screenshot 2: See the space between line 1 and line 2. This happens if I close output window. 

<img width="874" alt="screen shot 2017-09-07 at 8 53 13 am" src="https://user-images.githubusercontent.com/28315163/30165456-22dbe6a4-93ae-11e7-8460-be71bafa6fac.png">

<img width="788" alt="screen shot 2017-09-07 at 8 53 30 am" src="https://user-images.githubusercontent.com/28315163/30165468-2f7919cc-93ae-11e7-9ed4-369557784135.png">

**Comment by lgeiger** [comment] 2017-09-07 13:49
What Atom version are you using?

**Comment by srk-srinivasan** [comment] 2017-09-07 13:55
Atom version 1.19.6 X 64. 
OS: Mac os Sierra.

It was working fine till yesterday around 8 pm.

**Comment by srk-srinivasan** [comment] 2017-09-07 13:56
I deleted atom from entire system. Reinstalled from scratch. Reinstalled Hydrogen. yet this issue is lingering on.

**Comment by lgeiger** [comment] 2017-09-07 13:59
This looks like the issue was introduced by yesterdays release of Atom 1.19.6. I can reproduce this in Atom 1.20.0-beta6 as well.

**Comment by srk-srinivasan** [comment] 2017-09-07 14:02
Thank you for your prompt response. Any solution yet? or shall I wait till bug fixes?

**Comment by lgeiger** [comment] 2017-09-07 14:21
I'll open a issue on Atom.
For now I think the only solution is to downgrade to Atom 1.19.5 or use our external output area (*Hydrogen: Toggle output area*).

**Comment by srk-srinivasan** [comment] 2017-09-07 14:32
I am using Toggle output area as of now. Than you for such a quick response.

**Comment by lgeiger** [comment] 2017-09-07 19:39
This issue will be fixed in the upcoming bugfix release of Atom: https://github.com/atom/atom/pull/15583

**Closed by lgeiger** 2017-09-07 19:39 UTC

**Comment by lgeiger** [comment] 2017-09-08 11:02
Atom 1.19.7 and 1.20.0-beta7 are now published with a fix.

**Comment by bobbyangelov** [comment] 2017-09-23 11:08
Same here on ubuntu 16.04. Thanks for working on this!
