### ISSUE TITLE
Copy to clipboard function not working properly

### ISSUE THREAD

**Issue by illpack** [nteract/hydrogen#1077] opened 2017-11-02 09:21 UTC
**Description:**

After executing, the option _Copy to Clipboard_ only shows randomly (and not often). 

**Steps to Reproduce:**

![image](https://user-images.githubusercontent.com/16364365/32318405-177b9d54-bfaf-11e7-9a1f-36d5f85c4f04.png)

**Versions:**

Windows 7, Atom 1.21.2

**Comment by BenRussert** [comment] 2017-11-02 15:19
The icon will not appear if there isn't any text to copy. For example, if the output is an image.

**Comment by illpack** [comment] 2017-11-02 15:34
The icon appears randomly.
If there is text output, sometimes it appears but 90% of the times does not. 
Tested executing the same command that produces a line of text several times.
Can it be that Hydrogen interprets this output not as text but as something else on certain occasions?

Thanks,

**Comment by BenRussert** [comment] 2017-12-01 19:50
@illpack are you still experiencing this issue on the latest version of Hydrogen? If so, can you post a code example so I can try to reproduce?

**Comment by BenRussert** [comment] 2017-12-22 16:51
Closing since I believe this was fixed. Let us know if you have questions.

**Closed by BenRussert** 2017-12-22 16:51 UTC
