### ISSUE TITLE
Hydrogen Kernel persists through atom restart (tested only R)

### ISSUE THREAD

**Issue by sdrakulich** [nteract/hydrogen#1319] opened 2018-05-24 17:57 UTC
**Description:**

Anytime the kernel is not manually closed, it persists through atom being closed. Reopening and sending a command leads to the start of a new kernel.

I can shut those R sessions down through task manager, of course, and I was. However, atom and the computer lag with enough iterations of this, to the point of insane text-input lag.
With no R sessions running in task manager, and atom closed and reopened with only the packages necessary for running Hydrogen, it would still be unusable. Especially after calling on a new kernel.

Is this purely a "Hydrogen doesn't startup and check for running kernels it started itself"?

**Steps to Reproduce:**

1. Call R kernel
2. Exit and start atom, or ctrl+shift+F5. Either works.
3. Call R kernel
4. See (2) R sessions running in task manager, and the front end. Close them.
5. Keep doing this. The more R demanded of your system, the better. My situations have been a day or two of use, and then...
6. Your atom will become unusable, especially if you try calling a kernel. Just type, there's insane lag. Your computer will follow suit, but especially so if a Kernel is called upon. A computer restart clears this.

**Versions:**

- Windows 10
- Atom 1.27.1
- Hydrogen 2.5.0
- R version 3.5.0
- atom-ide-ui, atom-language-r, and hydrogen installed. Hydrogen functionality works, of course.

**Logs:**

The issue occurs when atom is exited. Whatever Hydrogen needs to do to shut down the kernel needs to be done. I can't provide this now, but I will if you need it. I hope you don't, I've done enough with this already. I would put it on my plate to help with this, but I'm 4 months into my first language, so I'll just apologize. Please fix this though, this seems like a big deal, and certainly feels like one.

**Comment by sdrakulich** [comment] 2018-05-30 01:02
Replicated on Linux today. Also bump, any official word here or?

**Comment by BenRussert** [comment] 2018-05-30 04:02
Thanks for the report!

Which R kernel is installed specifically? When you say "kernel manually closed" are you talking through task manager or through the hydrogen commands in the atom command palette?

**Comment by sdrakulich** [comment] 2018-05-30 16:30
I have tried manually closing the kernel before shutting atom down. When I said "manually closed", I mean both through that mechanism, and through "End Task" in process manager on the R runtime. Jupyter kernel does not appear for some reason, although it did on Ubuntu for me.

Either way, since Hydrogen detects that I have started a new session (can't close atom and reopen, then "connect to existing kernel", because there are no active kernels listed), there is some event-detection that can go on, if not on-close, then on-open instead.

By "which R kernel is installed", what do you mean? IRkernel as far as I know, and the latest version. I am running the latest versions of R and atom as well.

**Comment by sdrakulich** [comment] 2018-06-05 17:55
Verifying: "Shutdown Kernel" (within atom, running Hydrogen's command...) does nothing. R remains running, with full memory loaded in.

Again: manually shutting down this R instance **does not actually solve the issue.**
Somewhere, using Hydrogen is sapping massive amounts of memory, in a cumulative fashion.

I am going to openly ask: do you have any idea what is going on here?

**Comment by lgeiger** [comment] 2018-06-05 20:04
That's strange, I just verified that it works as expected with the Python kernel. 

Thanks for investigating, can someone else reproduce this issue too?

**Comment by BenRussert** [comment] 2018-06-09 11:13
> can someone else reproduce this issue too?

I have not been able to reproduce. I tried w/ IRkernel on ubuntu, but everything shut down fine. @sdrakulich are you running any code in R before attempting to shut down the kernel?

**Comment by sdrakulich** [comment] 2018-06-09 14:04
Yes, I run some code prior to trying to shut it down

**Comment by sdrakulich** [comment] 2018-08-01 16:05
I am going to bump this. Even shutting down the kernel using the command from within Atom leads to the R for Windows terminal front-end to continue running, and taking up all the memory it was before.

I have tested this on Linux, and using the shutdown Hydrogen Kernel command through Atom does indeed close all active processes.

**Comment by n-riesco** [comment] 2018-08-01 17:42
@sdrakulich If you run `q()` does the kernel die?

**Comment by sdrakulich** [comment] 2018-08-01 17:48
The kernel does, the R windows-front-end service does not

**Comment by n-riesco** [comment] 2018-08-01 18:33
@sdrakulich What do you mean by `"the R windows-front-end service does not"`? Do you mean that Hydrogen doesn't know that the kernel died? That would be expected.

I'm just trying to determine where the problem is. When the user runs the command `hydrogen:shutdown`, the following should happen:
1. Hydrogen sends `shutdown_request` to kernel
2. IRKernel receives `shutdown_request`
3. IRKernel sends `shutdown_reply` to Hydrogen
4. IRKernel invokes `quit()`
5. Hydrogen sends `SIGKILL` to IRKernel (in linux, this kills IRKernel if it hasn't died before; in windows, it doesn't work; this is a long standing issue with node in windows; a potential alternative is https://www.npmjs.com/package/tree-kill)

I see two possibles leads:
- find out why IRKernel doesn't invoke `quit()`
- or use `tree-kill` in Hydrogen

**Comment by wadethestealth** [comment] 2019-10-01 13:23
Closed by IRKernel/IRKernel#582

**Closed by wadethestealth** 2019-10-01 13:23 UTC
Labels: awaiting update, bug :bug:, help wanted, kernels, needs testing  :construction:
