### ISSUE TITLE
Cannot update hydrogen OS X Mojave 10.14.6

### ISSUE THREAD

**Issue by jvines** [nteract/hydrogen#1791] opened 2019-10-09 18:45 UTC
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hydrogen is unable to update wether via atom or via apm install hydrogen.

### Steps to Reproduce

apm install hydrogen, I guess

### Versions

OS version:
OS X Mojave 10.14.6

> `atom --version`

```
1.40.1
```

> `apm --version`

```
2.4.2
```

Hydrogen version:

2.10.3

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [x] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

```
> zeromq@5.1.0 install /private/var/folders/2_/h2fpfxyx1mv9gy_hgfmcyx180000gn/T/apm-install-dir-11999-24361-f932ob.27f1p/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 platform=darwin)

Building libzmq for darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... x86_64-apple-darwin13.4.0-clang
checking whether the C compiler works... no

npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
configure: error: in `/private/var/folders/2_/h2fpfxyx1mv9gy_hgfmcyx180000gn/T/apm-install-dir-11999-24361-f932ob.27f1p/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
child process exited with code 77
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/2_/h2fpfxyx1mv9gy_hgfmcyx180000gn/T/apm-install-dir-11999-24361-f932ob.27f1p/node_modules/Hydrogen/node_modules/zeromq
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/2_/h2fpfxyx1mv9gy_hgfmcyx180000gn/T/apm-install-dir-11999-24361-f932ob.27f1p/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-11999-24361-f932ob.27f1p No description
npm WARN apm-install-dir-11999-24361-f932ob.27f1p No repository field.
npm WARN apm-install-dir-11999-24361-f932ob.27f1p No README data
npm WARN apm-install-dir-11999-24361-f932ob.27f1p No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jvines/.atom/.apm/_logs/2019-10-09T18_41_33_265Z-debug.log
```

### Expected behavior

I expected to update hydrogen to version 2.12.1

Thanks for your time.

Jose Vines.

**Comment by wadethestealth** [comment] 2019-10-09 19:09
Duplicate of #1738. The issue here is your apm, you must update it to 2.4.3.

**Closed by wadethestealth** 2019-10-09 19:09 UTC
Labels: bug :bug:

**Comment by jvines** [comment] 2019-10-09 19:34
Great! Thank you very much, it resolved the problem. I'm sorry I didn't catch it was a duplicate!
