### ISSUE TITLE
Problem while trying to update/install hydrogen

### ISSUE THREAD

**Issue by amamaral** [nteract/hydrogen#2059] opened 2021-02-19 08:32 UTC
Dear, I was having problems to update Hydrogen. Uninstalled it and now I cannot reinstall. Atom shows the message below:

> Installing “Hydrogen@2.14.7” failed.Hide output…
> 
> npm ERR! Unexpected end of JSON input while parsing near '..."https://registry.npm'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\ander\.atom\.apm\_logs\2021-02-19T08_21_49_904Z-debug.log

The log file follows below. I'm not even sure if this is a bug in Hydrogen or Atom. What can I do? Thanks!

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\ander\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\ander\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\ander\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\ander\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/hydrogen/versions/2.14.7/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session 24544bd4c0578079
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/nteract/hydrogen/legacy.tar.gz/v2.14.7 1125ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/hydrogen/versions/2.14.7/tarball fetched in 1173ms
9 timing stage:loadCurrentTree Completed in 1200ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule Hydrogen@2.14.7 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime-corejs2 447ms (from cache)
18 silly pacote range manifest for @babel/runtime-corejs2@^7.0.0 fetched in 461ms
19 silly resolveWithNewModule @babel/runtime-corejs2@7.12.18 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/anser 434ms (from cache)
21 silly pacote range manifest for anser@^1.4.8 fetched in 452ms
22 silly resolveWithNewModule anser@1.4.10 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/atom-select-list 454ms (from cache)
24 silly pacote range manifest for atom-select-list@^0.7.0 fetched in 460ms
25 silly resolveWithNewModule atom-select-list@0.7.2 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/escape-carriage 128ms (from cache)
27 silly pacote range manifest for escape-carriage@^1.2.0 fetched in 130ms
28 silly resolveWithNewModule escape-carriage@1.3.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 273ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/@nteract%2fmathjax 751ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/jmp 288ms (from cache)
32 silly pacote range manifest for escape-string-regexp@^4.0.0 fetched in 304ms
33 silly resolveWithNewModule escape-string-regexp@4.0.0 checking installable status
34 silly pacote range manifest for @nteract/mathjax@^4.0.2 fetched in 788ms
35 silly resolveWithNewModule @nteract/mathjax@4.0.15 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/@nteract%2ftransform-vega 784ms (from cache)
37 silly pacote range manifest for jmp@^2.0.0 fetched in 321ms
38 silly resolveWithNewModule jmp@2.0.0 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/@nteract%2fcommutable 860ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/@nteract%2fmarkdown 862ms (from cache)
41 silly pacote range manifest for @nteract/transform-vega@^7.0.0 fetched in 856ms
42 silly resolveWithNewModule @nteract/transform-vega@7.0.10 checking installable status
43 http fetch GET 304 https://registry.npmjs.org/@nteract%2foutputs 870ms (from cache)
44 silly pacote range manifest for @nteract/commutable@^7.1.4 fetched in 892ms
45 silly resolveWithNewModule @nteract/commutable@7.4.2 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/@jupyterlab%2fservices 897ms (from cache)
47 silly pacote range manifest for @nteract/markdown@^4.5.1 fetched in 903ms
48 silly resolveWithNewModule @nteract/markdown@4.6.0 checking installable status
49 silly pacote range manifest for @nteract/outputs@^3.0.0 fetched in 918ms
50 silly resolveWithNewModule @nteract/outputs@3.0.11 checking installable status
51 silly pacote range manifest for @jupyterlab/services@^0.52.0 fetched in 952ms
52 silly resolveWithNewModule @jupyterlab/services@0.52.0 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/@nteract%2fplotly 940ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/kernelspecs 377ms (from cache)
55 silly pacote range manifest for @nteract/plotly@^1.48.3 fetched in 972ms
56 silly resolveWithNewModule @nteract/plotly@1.49.1 checking installable status
57 silly pacote range manifest for kernelspecs@^2.0.0 fetched in 429ms
58 silly resolveWithNewModule kernelspecs@2.0.0 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/lodash 348ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/mathjax-electron 358ms (from cache)
61 silly pacote range manifest for lodash@^4.14.0 fetched in 371ms
62 silly resolveWithNewModule lodash@4.17.20 checking installable status
63 silly pacote range manifest for mathjax-electron@^3.0.0 fetched in 375ms
64 silly resolveWithNewModule mathjax-electron@3.0.0 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/mobx 396ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/mobx-react 347ms (from cache)
67 silly pacote range manifest for mobx@^5.1.1 fetched in 433ms
68 silly resolveWithNewModule mobx@5.15.7 checking installable status
69 http fetch GET 304 https://registry.npmjs.org/react 345ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/react-dom 356ms (from cache)
71 silly pacote range manifest for mobx-react@^6.0.0 fetched in 398ms
72 silly resolveWithNewModule mobx-react@6.3.1 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/spawnteract 350ms (from cache)
74 silly pacote range manifest for react@^16.8.6 fetched in 405ms
75 silly resolveWithNewModule react@16.14.0 checking installable status
76 silly pacote range manifest for react-dom@^16.8.6 fetched in 405ms
77 silly resolveWithNewModule react-dom@16.14.0 checking installable status
78 silly pacote range manifest for spawnteract@^5.1.0 fetched in 379ms
79 silly resolveWithNewModule spawnteract@5.1.0 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/react-table 382ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/strip-indent 330ms (from cache)
82 silly pacote range manifest for react-table@^6.10.0 fetched in 399ms
83 silly resolveWithNewModule react-table@6.11.5 checking installable status
84 silly pacote range manifest for strip-indent@^3.0.0 fetched in 351ms
85 silly resolveWithNewModule strip-indent@3.0.0 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/styled-components 331ms (from cache)
87 silly fetchPackageMetaData error for styled-components@^5.0.1 Unexpected end of JSON input while parsing near '..."https://registry.npm'
88 http fetch GET 304 https://registry.npmjs.org/tildify 207ms (from cache)
89 silly pacote range manifest for tildify@^2.0.0 fetched in 211ms
90 silly resolveWithNewModule tildify@2.0.0 checking installable status
91 http fetch GET 304 https://registry.npmjs.org/uuid 210ms (from cache)
92 silly pacote range manifest for uuid@^8.0.0 fetched in 216ms
93 silly resolveWithNewModule uuid@8.3.2 checking installable status
94 http fetch GET 304 https://registry.npmjs.org/ws 190ms (from cache)
95 silly pacote range manifest for ws@^7.0.0 fetched in 196ms
96 silly resolveWithNewModule ws@7.4.3 checking installable status
97 http fetch GET 304 https://registry.npmjs.org/xmlhttprequest 897ms (from cache)
98 silly pacote range manifest for xmlhttprequest@^1.8.0 fetched in 899ms
99 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
100 timing stage:rollbackFailedOptional Completed in 1ms
101 timing stage:runTopLevelLifecycles Completed in 3435ms
102 silly saveTree apm-install-dir-2021119-3700-dlbkw1.eippo
102 silly saveTree `-- Hydrogen@2.14.7
102 silly saveTree   +-- @babel/runtime-corejs2@7.12.18
102 silly saveTree   +-- @jupyterlab/services@0.52.0
102 silly saveTree   +-- @nteract/commutable@7.4.2
102 silly saveTree   | `-- uuid@8.3.2
102 silly saveTree   +-- @nteract/markdown@4.6.0
102 silly saveTree   | `-- @nteract/mathjax@4.0.15
102 silly saveTree   |   +-- react-dom@16.14.0
102 silly saveTree   |   `-- react@16.14.0
102 silly saveTree   +-- @nteract/mathjax@4.0.15
102 silly saveTree   +-- @nteract/outputs@3.0.11
102 silly saveTree   +-- @nteract/plotly@1.49.1
102 silly saveTree   +-- @nteract/transform-vega@7.0.10
102 silly saveTree   +-- anser@1.4.10
102 silly saveTree   +-- atom-select-list@0.7.2
102 silly saveTree   +-- escape-carriage@1.3.0
102 silly saveTree   +-- escape-string-regexp@4.0.0
102 silly saveTree   +-- jmp@2.0.0
102 silly saveTree   +-- kernelspecs@2.0.0
102 silly saveTree   +-- lodash@4.17.20
102 silly saveTree   +-- mathjax-electron@3.0.0
102 silly saveTree   +-- mobx-react@6.3.1
102 silly saveTree   +-- mobx@5.15.7
102 silly saveTree   +-- react-dom@16.14.0
102 silly saveTree   +-- react-table@6.11.5
102 silly saveTree   +-- react@16.14.0
102 silly saveTree   +-- spawnteract@5.1.0
102 silly saveTree   +-- strip-indent@3.0.0
102 silly saveTree   +-- tildify@2.0.0
102 silly saveTree   +-- uuid@8.3.2
102 silly saveTree   +-- ws@7.4.3
102 silly saveTree   `-- xmlhttprequest@1.8.0
103 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."https://registry.npm'
103 verbose stack     at JSON.parse (<anonymous>)
103 verbose stack     at parseJson (C:\Users\ander\AppData\Local\atom\app-1.54.0\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
103 verbose stack     at C:\Users\ander\AppData\Local\atom\app-1.54.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
103 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:89:5)
104 verbose cwd C:\Users\ander\AppData\Local\Temp\apm-install-dir-2021119-3700-dlbkw1.eippo
105 verbose Windows_NT 10.0.19041
106 verbose argv "C:\\Users\\ander\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ander\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ander\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ander\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/hydrogen/versions/2.14.7/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
107 verbose node v12.4.0
108 verbose npm  v6.14.8
109 error Unexpected end of JSON input while parsing near '..."https://registry.npm'
110 verbose exit [ 1, true ]

**Comment by ramantehlan** [comment] 2021-04-05 03:39
Hi @amamaral,

I believe the issue is in installing one of the dependencies for hydrogen. More specifically, the parsing error. `Unexpected end of JSON input while parsing near ` 

I don't think it's an issue with the hydrogen package and is possibly related to your npm. You can try upgrading your NPM version and try reinstalling the package.

**Comment by aminya** [comment] 2021-04-15 03:43
Fixed by #2082

**Closed by aminya** 2021-04-15 03:43 UTC
Labels: install

**Comment by aminya** [comment] 2021-04-15 08:52
Hydrogen 2.15.0 is released. Now you can use Hydrogen on the latest Atom 🎉
