### ISSUE TITLE
Failed to install Hydrogen on latest version of Win 10.

### ISSUE THREAD

**Issue by BeyondAntares** [nteract/hydrogen#1204] opened 2018-01-27 08:44 UTC
**Description:**
I have a fresh install of window 10 with some basic software installed listed below with version history below. I received an error stating a file .eslintrc was not found in C:\users\Username directory. However upon looking into the folder the file is there and is 132 bytes.

**Steps to Reproduce:**

1. Within Atom's Package installer, searched for Hydrogen by nteract and clicked install
2. Installation package completes with the following error shown in error logs below, stating a missing file eslintrc is missing. 

**Versions:**
Software version history:
Windows 10, Build 17074 (pre-release 180116-1539)
Python 3.4.6
Anaconda 1.6.5
Atom 1.23.3 x64
Sublime v3 build 3143
VSCode 1.19.3

**Logs:**
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Username\.atom\packages\Hydrogen\node_modules\topojson-client\.eslintrc'
    at Error (native)
```

**Comment by BenRussert** [comment] 2018-01-30 18:06
There have been a number of installation issues recently caused by something upstream in atom. Can you try installing from the command line? `apm install hydrogen`

**Comment by mgdreamingstar** [comment] 2018-08-15 06:56
I can install Hydrogen by `apm install hydrogen`, but Atom say can't rebuild Hydrogen.

**Comment by BenRussert** [comment] 2018-08-15 19:00
Hi @mgdreamingstar, could you please open a new issue if you haven't opened one yet? I'm going to close this one since we didn't get a response on this one.

**Closed by BenRussert** 2018-08-15 19:00 UTC
