### ISSUE TITLE
'Restart kernel' and 'shutdown kernel' commands failing

### ISSUE THREAD

**Issue by wowserx** [nteract/hydrogen#863] opened 2017-06-07 15:34 UTC
**Description:**

Updated 'restart kernel' command doesn't properly restart the kernel. Run commands hang until kernel is restarted a second time, but only while a run command is hanging. 

Second (probably related) problem: Shutdown Kernel command after Restart Kernel command triggers invalid message tracebacks. 

**Steps to Reproduce:**

The sequence:

1. Restart Kernel
2. Run All
3. Restart Kernel

will properly run the program, but the sequence:

1. Restart Kernel
2. Restart Kernel
2.5 (...)
3. Run All 

will hang. 

The second problem can be reproduced as follows:

1. Run All
2. Restart Kernel
3. Shutdown Kernel
4. Run All

Produces the error message below, under Logs. 

**Versions:**

OSX 10.12.5 (16F73)
Atom 1.17.2 x64
Hydrogen 1.16.0

(Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
Jupyter : 4.1.0)

**Logs:**

[IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "/Users/$USERNAME/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 199, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "/Users/$USERNAME/anaconda/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: 'add5a85b80d1ed8600e3188d577977d087430339bdc0e46cff9ca8971c3222cd'

**Comment by t9md** [comment] 2017-06-08 11:31
![restart-callback-unstable](https://user-images.githubusercontent.com/155205/26926052-f100dd1a-4c86-11e7-9211-624c3111a774.gif)

I think this issue is related recently introduced faster-restart(#853).
I noticed similar issue(not same, but greatly related) while I'm working on #861(which call `runAll` on `restart` callback).

- If I passed callback to  `restart` like `restart(runAll)`, the issue is more happens. But % is still rare.
- I can't see issue with ijavascript kernel , but I can see issue for iPython kernel.
- If I launch Atom in dev-mode and open dev-tools, the issue in iPython kernel is almost always happen(means each restart-and-run-all).
- This is because, hydrogen write lots of logs in dev-console which add extra delay to complete kernel-restart(my assumption).
- If I add some delay by like`restart(()=> setTimeout(runAll, 1000))`, issue does not happen(of course this timeout would depends on CPU of client machine).

So my impression for this issue is, the timing of calling callback passed on restart is too early.

I think we have to find the way to correctly recognize timing for "when kernel.restart complete" in fast-restart situation.

**Comment by rgbkrk** [comment] 2017-06-12 00:28
Ok this is definitely seeming like doing the restart with the old connection file is a really bad idea since we aren't capturing the full lifecycle of closing down the old kernel (and it appears to still be responding with the old signature).

**Comment by lgeiger** [comment] 2017-06-16 23:09
Closed by #877

**Closed by lgeiger** 2017-06-16 23:09 UTC
Labels: bug
