### ISSUE TITLE
Request: strip _common_ leading whitespace from input before passing to kernel

### ISSUE THREAD

**Issue by sglyon** [nteract/hydrogen#862] opened 2017-06-07 14:29 UTC
I'd _love_ it if hydrogen stripped leading whitespace that was common to all lines in the selection before passing to the kernel.

For example, suppose I have this python code:

```python
def build_grids(p: Params):
    # build grid over I choices and N states
    Imax = 10
    expected_life = (1-p.δ) / p.δ
    Igrid = np.arange(1, Imax+1)
    Ngrid = np.arange(0, round(Imax*expected_life)+1, 2)

    zgrid = p.z
    # ... more code ....
```

If I were to highlight from the start of the commented line `    # build grid...` (including the leading whitespace) all the way to `p.z`, and try to evaluate I would get a complaint from the python kernel about unexpected whitespace. 

If I were to take that same highlighted region and copy it to my system clipboard and then use the `%paste` magic in an ipython terminal session, the leading whitespace would be stripped and evaluation would proceed without errors.

Note that in my example if I were to start my selection at the `I` character in `Imax` then the behavior should be to still throw an error because the first line in my selection doesn't have leading whitespace in common with all other lines.

I was going to try to take a stab at this, but I don't know where to look inside here. I figured you would know better than me ;)

**Comment by BenRussert** [comment] 2017-06-12 19:16
My first impression is that there isn't a truly language agnostic way to do this from hydrogen's end. 

Interesting issue, I think an init script or plugin solution could be fairly straight forward, but I'm not sure this should be built into hydrogen itself.

**Comment by rgbkrk** [comment] 2017-06-13 02:49
Is there a precedent for this with the jupyter notebook?

**Comment by sglyon** [comment] 2017-06-13 02:51
No, the notebook doesn't do this, but the console does... with the `%paste` magic:

<img width="1284" alt="screen shot 2017-06-12 at 10 50 29 pm" src="https://user-images.githubusercontent.com/1001948/27063766-ac0d5b6e-4fc1-11e7-9a5c-da576a2d792a.png">

```
~|⇒ ipython                                                                                       vpn-192-168-100-7
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
   ...:     def foo():
   ...:         return "hello!"
   ...:
   ...:
   ...:     foo()
  File "<ipython-input-1-ede5e3b3ed2a>", line 2
    def foo():
    ^
IndentationError: unexpected indent


In [2]: paste

    def foo():
        return "hello!"


    foo()

## -- End pasted text --
Out[2]: 'hello!'
```

**Comment by BenRussert** [comment] 2017-06-13 02:53
It may not be an issue in notebook since it normally runs code in cells instead of selection based

**Comment by sglyon** [comment] 2017-06-13 02:55
Good point ☝️ 

I think that is the main reason I've never missed that in the notebook, but am happy to have it in the console and would like to see it here. 

If I were to try to put this in my init script is there a recommended way for me to add a processing layer before hydrogen sends code to the kernel?

**Comment by BenRussert** [comment] 2017-06-13 03:35
> If I were to try to put this in my init script is there a recommended way for me to add a processing layer before hydrogen sends code to the kernel?

Not exactly, (yet :smile: ) .

Now that I think it through in order to use the init solution you would probably need to change the actual text buffer in selection then change it back after dispatching `hydrogen:run`. Could get pretty janky.

I think in this case the best way to enable this would be through enhancing our plugin api (something we have talked about doing for other reasons anyway).

**Comment by nikitakit** [comment] 2017-06-13 05:49
This issue is something I've been running into as well in my usage. I wouldn't be opposed to having hydrogen strip out common leading whitespace, rather than offloading this to a plugin. The criteria for this are pretty simple (detect leading whitespace on first line, and strip it from later lines) so it doesn't actually require any language-specific parsing.

**Comment by BenRussert** [comment] 2017-06-13 11:26
It would be language specific just in the sense that there is no need to do this in most languages (the described workflow works fine in julia, js, R, etc.)

on the other hand, I guess if we are doing any language a favor it should be Python.

My other concern would be: can this have side effects for other kernels? Seems unlikely, but something to think about.

**Comment by t9md** [comment] 2017-06-13 13:49
I agree with @BenRussert, but still want this feature supported by hydrogen.
Since it's just simple and easy than ask/wait for each kernel provider to support this.

How about implement this indent removing feature and make it configurable by scope name.

- Add `stripIndentBeforeSendToKernel` config with default `['source.python']`.
- When editor have matching scope, strip leading whilte-space(=indent) before sending to kernel.

One side effect for this is, code is evaluated in same environment unless restarting kernel.
If user selected some deep indented lines of code, it evaluated as no indented level, this affect **scope** of vars its effective depending on language.
But this is also true for `hydrogen:run` it can change order of code evaluated, so user have to being careful for the effect of these commands anyway.

**Comment by n-riesco** [comment] 2017-06-13 15:31
I think this should really in its own command (and likely in a language-specific plugin). Otherwise, if trimming was the default behaviour, how would we handle:
- multi-line strings?
- and the pollution of the global scope?

**Comment by lgeiger** [comment] 2017-06-14 14:58
I think it would be OK to strip whitespace on code that is executed on a selection basis.

We could quite easily add this [here](https://github.com/nteract/hydrogen/blob/master/lib/code-manager.js#L49) since we already normalize the line endings before sending code to a kernel.

> how would we handle multi-line strings?

Is this really a problem if leading whitespace is stripped?

> how would we handle the pollution of the global scope?

I don't think we need to handle this case. Right now one can already execute deeply nested code by selecting it line by line. Stripping the whitespace only makes it convenient to execute multiple nested lines.

**Comment by BenRussert** [comment] 2017-06-14 15:57
@lgeiger Good points. 

I like @t9md's thoughts above about how to make this configurable by scope name. It seems like a good thing to make configurable just in case.

**Comment by kkonevets** [comment] 2017-12-04 13:59
pyCharm can handle this issue pretty good, why can't hydrogen do the same?

**Comment by nikitakit** [comment] 2018-02-02 01:59
I thought that updates to the plugin API would make it easy to implement this feature as a plugin, but it turns out that this is not the case.

It so happens that hydrogen always trims the string before sending it to the kernel, so e.g.
```
    x = 5
    print(x)
```

becomes 
```
x = 5
    print(x)
```
and it's rather difficult for a plugin to undo that transformation.

(Just wanted to post this thought here in case it sparks any ideas)

**Comment by nikitakit** [comment] 2018-02-21 21:30
Now that the plugin API changes are merged, it's possible to *mostly* implement this feature in a plugin. I have a working plugin implementation at https://github.com/nikitakit/hydrogen-python

Note that there are some limitations (related to my comment above), but at least in my code those cases occur infrequently compared to the many times I want to run code in an indented block.

**Comment by kylebarron** [comment] 2018-07-30 03:07
In @sglyon's [comment](https://github.com/nteract/hydrogen/issues/862#issuecomment-307991606), he has:

```
In [1]:
   ...:     def foo():
   ...:         return "hello!"
   ...:
   ...:
   ...:     foo()
  File "<ipython-input-1-ede5e3b3ed2a>", line 2
    def foo():
    ^
IndentationError: unexpected indent

```

Did this behavior change between IPython 5 and IPython 6? Because it works now:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/15164633/43375585-081c1092-9384-11e8-8862-89497f499451.png">

**Comment by kylebarron** [comment] 2018-07-30 03:14
I reproduced this in IPython 5.3.0, and it works fine. 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/15164633/43375694-9a7a479c-9384-11e8-96fe-b1e1af6f5005.png">

The reason why it didn't work in the above comment is because there's a silent `\n` on line 1, hence why the `IndentationError` is raised on line 2. 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/15164633/43375728-d447cb8e-9384-11e8-93a0-bd5f02ee6305.png">

Given that IPython is fine with common whitespace, as long as Hydrogen doesn't remove leading whitespace, this issue should be solved. See https://github.com/nteract/hydrogen/pull/1363.

**Closed** 2018-07-31 13:02 UTC
Labels: enhancement, language specific, plugin-idea
