### ISSUE TITLE
Hydrogen Python freezes

### ISSUE THREAD

**Issue by tusing** [nteract/hydrogen#55] opened 2015-06-10 20:47 UTC
So, I have a Python file open - fresh startup.

I select the first block of code I want to run - 2 import statements and 2 string variable definitions. Unfortunately, Hydrogen seems to go into an infinite loop, and the loading bar is displayed forever.

This doesn't happen if I have a fresh file and I evaluate the block line by line. But whenever this happens, interrupting or restarting the python kernel from Hydrogen doesn't seem to work.

**Comment by n-riesco** [comment] 2015-06-10 20:57
I've experienced something similar. Does it work after you save the file? If so, this is issue https://github.com/willwhitney/hydrogen/issues/53

**Comment by n-riesco** [comment] 2016-03-09 12:38
@tusing I'm closing this issue as duplicate of #53 . Please, feel free to reopen if this is not the case.

**Closed by n-riesco** 2016-03-09 12:38 UTC
