### ISSUE TITLE
Invalid Syntax error on multi-line values

### ISSUE THREAD

**Issue by jeremyechols** [nteract/hydrogen#904] opened 2017-07-03 19:56 UTC
**Description:**

When creating multi-line values, such as a dictionary, I am receiving an 'invalid syntax' error when trying to run Hydrogen within Atom. However, if I run the dictionary as a long single line, Hydrogen runs fine. 

I have tested the multi-line code within my Jupyter notebook, and have run the .py file through Terminal with the multi-line code saved and both run just fine. Hydrogen is the only thing that I try to run that is having the issue.

**Steps to Reproduce:**

1. Create multi-line value (dictionary in this case).
2. Run hydrogen (shift+return)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Mac OS - 10.12.5
Atom - 1.18.0
Hydrogen - 1.18.0

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).
File "<ipython-input-4-72375477343a>", line 1
    'population': [200.4, 143.5, 1252, 1357, 52.98]}
                                                   ^
SyntaxError: invalid syntax

When using this dictionary:
worldDict = {'country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
             'capital': ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
             'area': [8.516, 17.10, 3.286, 9.597, 1.221],
             'population': [200.4, 143.5, 1252, 1357, 52.98]}
![image](https://user-images.githubusercontent.com/15058286/27806363-fe025fd6-5fee-11e7-8c01-d3fd66d32438.png)

**Comment by agiap** [comment] 2017-07-11 17:53
I encounter the same issue with multi-line sections that I try to execute in one shot with Hydrogen.

**Comment by jeremyechols** [comment] 2017-07-11 20:22
I have figured out that when declaring a variable and assigning a value to it, you have to run the code from the top line (seems inconvenient, when I'm wanting to run the code upon completion of typing the values, but I get it). 

However, I have not figured out a workflow to make if/elif/else statements run within Hydrogen.

**Comment by rgbkrk** [comment] 2017-07-13 15:02
> However, I have not figured out a workflow to make if/elif/else statements run within Hydrogen.

I select all the text I want to run and hit cmd-enter (`hydrogen: run` command).

**Comment by lgeiger** [comment] 2017-07-14 10:46
You can also use [cells](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell) to run predefined code blocks.

I'm going to close this as a duplicate of #724. Please take a look at #724 for more information.

**Closed by lgeiger** 2017-07-14 10:46 UTC
