### ISSUE TITLE
Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Re...

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#793] opened 2017-05-20 14:18 UTC
[Enter steps to reproduce:]

1. launch hydrogen
2. open pdf

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.13.0

### Stack Trace

Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'

```
At /Users/me/.atom/packages/Hydrogen/node_modules/requirejs/bin/r.js:2607

Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1946:33)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1133:51)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1935:21)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1084:29)
    at Object.fetch (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1074:66)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1106:30)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1807:39)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1411:33)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:384:23
    at each (/packages/Hydrogen/node_modules/requirejs/bin/r.js:309:31)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1363:17)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1710:36
```

### Commands

```
     -0:54.6.0 core:save (input.hidden-input)
     -0:51.3.0 core:backspace (input.hidden-input)
     -0:50.5.0 core:save (input.hidden-input)
  3x -0:47.2.0 editor:newline (input.hidden-input)
     -0:39.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
ask-stack 2.2.0 
atom-beautify 0.29.24 
atom-python-run 0.7.3 
auto-encoding 0.7.0 
auto-update-packages 1.0.1 
autocomplete-python 1.8.63 
autocomplete-R 0.6.0 
browser-plus 0.0.87 
build 0.67.0 
build-rscript 0.6.1 
busy 0.7.0 
busy-signal 1.4.1 
data-atom 0.25.1 
Ensime 0.41.0 
gist 0.4.0 
git-projects 1.17.0 
Hydrogen 1.13.0 
hyperclick 0.0.40 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
kite 0.23.0 
language-latex 1.0.0 
language-markdown 0.22.0 
language-pgsql 0.2.3 
language-r 0.4.1 
language-scala 1.1.8 
language-sql-mysql 0.3.1 
latex 0.43.0 
latex-autocomplete 1.0.0 
latextools 0.8.5 
linter 2.1.4 
linter-ui-default 1.2.4 
markdown-preview-plus 2.4.9 
open-recent 5.0.0 
pdf-view 0.58.0 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
qolor 0.4.1 
quick-query 0.9.2 
r-exec 0.5.0 
sbt 0.11.0 
scala-format 0.1.8 
sync-settings 0.8.1 
tasks 2.6.6 
todo-show 1.11.0 
```

**Comment by buyology** [comment] 2017-05-20 16:21
Thanks for the bug report! Seems to be the same issue as in #777 and #616

Confirmed that it fails if you first run Hydrogen and then open a pdf, but works if you first open the pdf and then start a kernel

It seems that instead of pointing to the expected `/<atom package dir>/atom-pdf-view/pdfjs-dist/build/pdf.worker.js` the pdf workerSrc is set to `/Atom.app/Contents/Resources/app/static/~`, where it obviously can't find `pdf_worker.js`

cc @izuzak

**Comment by hugeme** [comment] 2017-05-20 16:25
Yes the other way around ist fine :)

**Comment by buyology** [comment] 2017-05-20 16:29
yes, that's a possible work around 👍 reopening this however so we can get it fixed :hole: :bug:

**Comment by izuzak** [comment] 2017-05-26 07:46
Thanks for the ping, @buyology :bow:, but I'm not sure I understand what kind of input you're expecting from me here (as the developer of that package). Could you please be a bit clearer about that? 🙏 

I just tried using the latest version of the atom-pdf-view package in the latest version of Atom and it worked just fine for me. I don't use hydrogen and the package wasn't really built with hydrogen in mind. If there's anything you'd like for the package to do differently -- I'd recommend submitting a more detailed issue (or even better a pull request) over at https://github.com/izuzak/atom-pdf-view.

**Comment by BenRussert** [comment] 2017-06-13 23:08
@buyology Do you think we should close this? I'm just thinking it has to do with some dependency so not sure what we could do about it. @izuzak is probably in the same boat.

Added the help wanted tag since I'm :man_shrugging: on this one.

**Closed** 2017-10-13 04:52 UTC
Labels: help wanted
