### ISSUE TITLE
Uncaught TypeError: Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by samik31** [nteract/hydrogen#1586] opened 2019-04-07 14:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'has' of undefined

```
At /Users/samiK/.atom/packages/Hydrogen/lib/utils.js:122

TypeError: Cannot read property 'has' of undefined
    at isMultilanguageGrammar (/packages/Hydrogen/lib/utils.js:122:25)
    at Object.getCurrentCell (/packages/Hydrogen/lib/code-manager.js:275:7)
    at Object.runCell (/packages/Hydrogen/lib/main.js:522:40)
    at HTMLElement.hydrogenRunCell (/packages/Hydrogen/lib/main.js:110:41)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694296)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:701680)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:21.2.0 hydrogen:run (input.hidden-input)
     -1:21.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:54.7.0 hydrogen:run (input.hidden-input)
     -0:54.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:48.6.0 hydrogen:run (input.hidden-input)
     -0:48.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:42.1.0 core:save (input.hidden-input)
     -0:38.2.0 hydrogen:run (input.hidden-input)
     -0:38.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:34.7.0 editor:newline (input.hidden-input)
     -0:32.2.0 core:backspace (input.hidden-input)
     -0:30.2.0 core:move-down (input.hidden-input)
     -0:27.5.0 hydrogen:run (input.hidden-input)
     -0:27.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:15.1.0 hydrogen:run-cell (input.hidden-input)
     -0:15.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
busy-signal 2.0.1 
french-menu 0.2.2 
git-plus 8.6.2 
Hydrogen 2.8.0 
hydrogen-python 0.0.8 
hydrogen-xdbg 0.0.4 
intentions 1.1.5 
linter 2.3.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
material 2.2.0 
material-dark-soda-ui 1.0.1 
minimap 4.29.9 
```

**Comment by BenRussert** [comment] 2019-04-12 00:42
Are you able to get the same error again? If so can you share the steps to repro? Thanks!

**Comment by wadethestealth** [comment] 2019-05-25 15:43
@samik31 Are you able to reproduce this?

**Comment by samik31** [comment] 2019-05-25 17:08
hi,
I don’t have the issue yet,  I am not able to satisfy your request , sorry.

**Comment by wadethestealth** [comment] 2019-06-03 23:33
Closing this for now because this error should be impossible since its called on a global file constant. If you see it again open a new issue with how you produced it.

**Closed by wadethestealth** 2019-06-03 23:33 UTC
