### ISSUE TITLE
Import Notebook opens two untitled documents

### ISSUE THREAD

**Issue by Rodrigo163** [nteract/hydrogen#1648] opened 2019-06-04 12:55 UTC
**Description:**

When I create a new .ipynb file in atom and ask hydrogen to import the notebook nothing happens.
When importing existing notebooks (created in Jupyter Lab), atom opens two untitled notebooks with the desired imported content, but once one of those two files is saved it is not importable again. 

**Steps to Reproduce:**

1. [create new .ipynb file]
2. [try to import notebook]
3. [import existing .ipynb]
4. [try to save one of the two untitled documents created on step 3.]
**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Windows 10 with Atom 1.37
You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [ .] hydrogen-python
- [.] Hydrogen Launcher
- [.] Data Explorer

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by wadethestealth** [comment] 2019-06-04 14:04
@Rodrigo163 I am able to reproduce the empty notebook not opening (this should probably throw an error of some kind), but I am unable to see two untitled notebooks when opening an existing notebook.

**Comment by Rodrigo163** [comment] 2019-06-04 16:10
Thank you for the fast reply!
You're right, I was double tapping the file. Here is what I mean with the untitled document.

![Hydrogen_bug](https://user-images.githubusercontent.com/10538562/58895327-ed6c8d80-86f3-11e9-8e72-54c69ca3cf50.gif)

**Comment by wadethestealth** [comment] 2019-06-04 16:17
@Rodrigo163 ahh I see. So instead of editing your notebook directly, hydrogen opens an untitled document that is an equivalent that you must save as whatever file extension you desire (just not `.ipynb`) once you are done editing, you can export that file back to an `.ipynb`. I am closing this issue, since this is expected behavior of hydrogen, but feel free to ask more questions.

**Closed** 2019-06-04 16:18 UTC
