### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by JavierBejMen** [nteract/hydrogen#1595] opened 2019-04-14 20:25 UTC
[Enter steps to reproduce:]

1. launch atom

**Atom**: 1.36.0 x64
**Electron**: 4.1.4
**OS**: linux 5.0.7-arch1-1-ARCH
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.9.0

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/zes/.atom/packages/Hydrogen/node_modules/vega-lib/build/vega.js:110

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (<anonymous>)
    at field (/packages/Hydrogen/node_modules/vega-lib/build/vega.js:110:7)
    at /packages/Hydrogen/node_modules/vega-lib/build/vega.js:118:12
    at isArray (/packages/Hydrogen/node_modules/vega-lib/build/vega.js:2:66)
    at /packages/Hydrogen/node_modules/vega-lib/build/vega.js:5:2)
    at /packages/Hydrogen/node_modules/vega-lib/build/vega.js:38114:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at xhtml (/packages/Hydrogen/node_modules/vega-embed/build/vega-embed.js:2:91)
    at /packages/Hydrogen/node_modules/vega-embed/build/vega-embed.js:5:2)
    at /packages/Hydrogen/node_modules/vega-embed/build/vega-embed.js:3473:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/Hydrogen/node_modules/@nteract/transform-vega/lib/index.js:36:41)
    at /packages/Hydrogen/node_modules/@nteract/transform-vega/lib/index.js:178:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
Hydrogen 2.9.0 
ide-python 1.4.1 
```

**Comment by BenRussert** [comment] 2019-04-14 20:29
Duplicate of #1591

**Closed by BenRussert** 2019-04-14 20:29 UTC
