### ISSUE TITLE
Allow Hydrogen to work if Atom isn't started from the Terminal

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#176] opened 2016-02-24 21:54 UTC
I did a bit of research on this topic and found this solution (https://discuss.atom.io/t/atom-command-doesnt-pass-environment-variables-to-atom/1596) that worked for me on Mac.

I added the following to my Init Script of Atom.
```
{exec} = require 'child_process'

# This command should generate a list of all exports from a login shell:
exportsCommand = process.env.SHELL + " -lc env"

# Run the command and update the local process environment:
exec exportsCommand, (error, stdout, stderr) ->
	for definition in stdout.trim().split('\n')
		[key, value] = definition.split('=', 2)
		process.env[key] = value
```
This allows Atom to get the correct PATH variables. Now Atom can be started as an app and Hydrogen works without compromises.

If this works on Windows and Linux as well, I think we should consider adding this hack to the Wiki.

**Comment by slavaGanzin** [comment] 2016-02-25 13:52
Maybe, I said just maybe. Launch such code at preinstall as here: https://github.com/nteract/hydrogen/commit/9564649746729a97a5556dcb2813425c05574944#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L29

And save it to options? So you can edit your hydrogen PATH.

I don't need this functionality at all, so just curious

**Comment by themiguelamador** [comment] 2016-03-14 02:25
I can run Julia without opening from terminal since ever on Mac...

**Comment by rgbkrk** [comment] 2016-03-14 03:21
> I can run Julia without opening from terminal since ever on Mac...

I'll bet that's because your kernel is installed properly, as is the case for non-Python kernels (the default kernel of `jupyter`'s Python is not installed to a kernelspec directory by default).

**Comment by slavaGanzin** [comment] 2016-03-14 10:39
Is this issue actual? I thought, Hydrogen launch ```jupyter kernelspec``` and so it shouldn't depend on the way atom was launched.

**Comment by lgeiger** [comment] 2016-03-14 12:30
I tried again with the latest version of Hydrogen and it works now with the python kernel. That wasn't the case with version 0.6.5.

The only problem is, python modules wich are not installed in the standard directory are not detected by hydrogen. Is there any way of telling hydrogen where to find them?

**Comment by lgeiger** [comment] 2016-03-14 13:09
I can put the path to the external python module in my init script and everything works as expected:
`process.env.PYTHONPATH = ['/usr/local/opt/root6/lib/root', process.env.PYTHONPATH].join(':')`

Is there an easy language independent way to tell hydrogen where to find external packages in the settings?
If this is some special use case wich would be hard to include in hydrogen feel free to close this issue.

**Comment by n-riesco** [comment] 2016-03-14 13:40
Does this issue affect Windows?

Is this issue limited to Mac?

If it's limited to Mac (or Windows isn't affected), a solution simpler than [this](https://github.com/nteract/hydrogen/issues/176#issue-136197899) would be:

```js
        if @language == 'python' and not @kernelInfo.argv?
            commandString = "ipython"
            args = [
                "kernel",
                "--no-secure",
                "--hb=#{@config.hb_port}",
                "--control=#{@config.control_port}",
                "--shell=#{@config.shell_port}",
                "--stdin=#{@config.stdin_port}",
                "--iopub=#{@config.iopub_port}",
                "--colors=NoColor"
                ]
	    if process.platform is "darwin"
	        commandString = process.env.SHELL
		args = [
		    "-lc",
		    "ipython",
		].concat(args)

        else
            commandString = _.first(@kernelInfo.argv)
            args = _.rest(@kernelInfo.argv)
            args = _.map args, (arg) =>
                if arg == '{connection_file}'
                    return @configPath
                else
                    return arg

        console.log "launching kernel:", commandString, args
        @kernelProcess = child_process.spawn(commandString, args, {
                cwd: projectPath
            })
```

**Comment by lgeiger** [comment] 2016-03-14 14:36
@n-riesco I don't know. I can't test on Windows.

**Comment by n-riesco** [comment] 2016-03-14 16:18
The bug doesn't seem to affect Ubuntu 14.04 when the kernelspec is set to:

```json
{
    "kernelspecs": {
        "ipython": {
            "spec": {
                "display_name": "IPython",
                "env": {},
                "argv": [
                    "ipython",
                    "kernel",
                    "--no-secure",
                    "--colors=NoColor",
                    "-f",
                    "{connection_file}"
                ],
                "language": "python"
            }
        }
    }
}
```

**Comment by lgeiger** [comment] 2016-03-15 00:30
I have this problem just with one python module which wasn't installed via `pip` and isn't located in the default python directory. So maybe this isn't hydrogens fault but rather the package itself.

**Comment by n-riesco** [comment] 2016-03-15 07:12
On 15/03/16 00:30, Lukas Geiger wrote:
> I have this problem just with one python module which wasn't installed via |pip| and isn't located in the default python directory. So maybe this isn't hydrogens fault but rather the package itself.

Perhaps, I'm misunderstanding the issue. Could you describe how to reproduce it?

**Comment by lgeiger** [comment] 2016-03-15 10:35
Yeah my description wasn't clear at all:

I have python and all my modules installed via `pip` in the default location. So far Hydrogen works as expected. There is no difference if Hydrogen is started from the terminal or as an app.

Now to my problem:
I have one python module which is installed as part of an software package (https://root.cern.ch/pyroot) in a different directory. The installation sets the `PYTHONPATH` variable so that python is able to find it.
If Atom is started from the command line, it sees the `PYTHONPATH` variable and I can import the module.

If Atom is started as an app, it doesn't see the `PYTHONPATH` and cannot import this module. I can manually set the path in the `init` file with `process.env.PYTHONPATH = ['/usr/local/opt/root6/lib/root', process.env.PYTHONPATH].join(':')` and then Hydrogen works fine again.

For me this isn't a big issue anymore, because I only have one module installed in a non default directory. But it would be nice if it can be fixed for people who don't like messing with their `init` file.

**Comment by n-riesco** [comment] 2016-03-15 10:48
@lgeiger This may be an issue on where your system sets PYTHONPATH. In my machine, when I run Atom using a .desktop file, I have no problem to see the environment variables set in `~/.profile`.

**Comment by n-riesco** [comment] 2016-03-15 10:59
@rgbkrk Is there still an issue on Mac? Are the user's environment variables visible when Atom isn't run from a terminal?

**Comment by rgbkrk** [comment] 2016-03-15 13:50
This should be solved *soon*, with a coming Atom release:

See:

* https://github.com/atom/atom/issues/6956
* https://github.com/atom/atom/pull/11054

**Comment by n-riesco** [comment] 2016-03-15 14:05
@lgeiger Shall we close this issue?

**Closed** 2016-03-15 14:06 UTC
