### ISSUE TITLE
Python 3 Kernel Issue

### ISSUE THREAD

**Issue by GathererA** [nteract/hydrogen#1665] opened 2019-06-18 00:12 UTC
**Description:**

I have a Windows 10 laptop that I am trying to run hydrogen through atom on for a Python 3 use case. I have installed anaconda and ipykernel using the instructions detailed on the nteract website associated with Hydrogen but I am receiving consistently some error with the kernel that I am using. 

**Steps to Reproduce:**

**Versions:**

Windows 10
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Plugins:**

No plug-ins active

**Logs:**

```
Traceback (most recent call last): 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\runpy.py", line 85, in _run_code exec(code, run_globals) 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) 
File "C:\Users\andrew.gatherer\anaconda3\envs\my_conda\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.
```

**Comment by aviatesk** [comment] 2019-06-21 19:07
This issue seems to lie not on Hydrogen side, but just on Anaconda's.
The last line says you may not set the env path properly. Setting env paths to `anaconda3/your-env/share/` or somewhere else might help.

@GathererA 
I'm going to close this issue cause Hydrogen doesn't seem to have to handle this kind of issue.
But feel free to reopen this if you find this issue is actually caused by Hydrogen.

**Closed by aviatesk** 2019-06-21 19:07 UTC
Labels: help wanted, install, kernels, windows
