### ISSUE TITLE
UPDATE: Bug: cannot start kernel in directory of file

### ISSUE THREAD

**Issue by ericmjl** [nteract/hydrogen#1252] opened 2018-03-06 14:07 UTC
**Description:**

I have a project with the following directory structure.

```
- project/
    - utils/
        - __init__.py
        - data.py
    - other_folder/
    - more_folders/
    - README.md
```

I'm trying to interactively edit and modify `data.py`. Inside `data.py`, I have some relative imports:

```python
# data.py
from .__init__ import variable1, function1  # variable1 and function1 are defined in .__init__.py
# more code below
```
With `data.py` open, I start a hydrogen kernel. I then try to execute the import line, resulting in the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e196e29d3a5c> in <module>()
----> 1 from .__init__ import injection_stages, stages

ModuleNotFoundError: No module named '__main__.__init__'; '__main__' is not a package
```

I had to dig around in the settings to learn that I could start a hydrogen kernel in a variety of places. However, I could not find documentation about this. 

Having switched the setting from "The first started project's directory" to "Current directory of the file", followed by a restart of Atom, I still found that I could not properly import that line of code, getting the same error.

Is this a legitimate bug that I have found, or am I missing something that might fix this issue?

**Comment by nikitakit** [comment] 2018-03-06 15:24
I suspect that relative imports simply don't work inside Jupyter. If you create a notebook `test.ipynb` inside `utils/` and run `from .init import variable1` from the notebook, I'm pretty sure you'll get the same error.

Based on the error message, the issue is not that python can't find `__init__.py` but that `data.py` is being run as a main script instead of as a package. For example, running `python utils/data.py` is not the same as doing `import utils.data` from a higher level.

This behavior is quite disappointing, but to the best of my knowledge it's not exclusive to hydrogen. 

Maybe someone more familiar with IPython knows a solution. (For me personally, the way I get around issues like this is by using a package I wrote called [xdbg](https://github.com/nikitakit/xdbg) and the `%scope`/`%makescope` magics it provides.)

**Comment by ericmjl** [comment] 2018-03-06 16:49
@nikitakit thanks for the pointer. Indeed yes, relative imports don't work -- I only had to open IPython to confirm that. 

Thanks for pointing out xdbg as well - it's something I'll give a shot at using in the near future!

**Comment by BenRussert** [comment] 2018-09-21 00:56
Stumbled on this looking for another issue, looks like we can close this!

**Closed by BenRussert** 2018-09-21 00:56 UTC
