### ISSUE TITLE
does not show print output in a hydrogen bubble 

### ISSUE THREAD

**Issue by qixiang109** [nteract/hydrogen#326] opened 2016-07-07 03:52 UTC
all features work  but the "print" function doesn't show the output in a bubble, but only with a √ mark to the right.  I am using an anaconda python. It this a problem of anaconda?

**Comment by lgeiger** [comment] 2016-07-07 08:17
I can't reproduce this. Could you try to run Hydrogen again and open the dev console (shift-ctrl-i) and post a screenshot of the output.

**Comment by qixiang109** [comment] 2016-07-11 11:27
today when I tried again, the problem disappeared, I don't know why, but it suddenly works. Thank you for your reply,  fantastic package!

**Comment by pierregodard** [comment] 2016-07-22 14:57
@lgeiger, i have a similar problem, except that i don't even see a check mark. nevertheless, as in ([#88](https://github.com/nteract/hydrogen/issues/88)), i can connect to the jupyter kernel outside of hydrogen and check for example that a variable was instantiated and the code properly executed, or add a watch which will function as expected.

Here is the result of `apm -v`on a mac running OS X 10.11.6:
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2
```
Executing a "Run and Move Down" on `print("hello")` gives me the following output in the console:

<img width="1190" alt="screen shot 2016-07-22 at 16 47 09" src="https://cloud.githubusercontent.com/assets/4210161/17060911/4c719cf0-502c-11e6-8871-f40a3fe880d0.png">

I hope i'm not missing something obvious. Tell me if i can provide more useful information, I hope to be able to use this exciting package soon!

**Comment by lgeiger** [comment] 2016-07-22 15:08
@pierregodard Which hydrogen version are you using? We fixed an issue with "Run and Move Down" in the latest release.

Is just "Hydrogen: Run" working for you?

**Comment by pierregodard** [comment] 2016-07-22 15:29
thank you for your answer Lukas. i use Hydrogen 0.11.0 and unfortunately "Hydrogen: Run" doesn't work either.

**Comment by lgeiger** [comment] 2016-07-22 15:59
This is very strange. I have pretty much the same setup and no problems.

**Comment by n-riesco** [comment] 2016-07-22 16:13
And what Atom version?

**Comment by pierregodard** [comment] 2016-07-22 16:17
my Atom version is 1.8.0

**Comment by n-riesco** [comment] 2016-07-22 16:24
I've tested Atom 1.8.0 and 1.9.0, and I can't reproduce it.
I've tried the UI themes `One Light` and `Atom Light`.
Which UI theme are you using?

**Comment by pierregodard** [comment] 2016-07-22 16:35
i use `One Light`  (with `Base 16 Tomorrow Light`)  but same effect with `One Dark` (and `Solarized Dark`)

**Comment by n-riesco** [comment] 2016-07-22 16:49
The most intriguing thing is that the log in the screenshot looks perfectly normal.

Could you run in the console the code `document.getElementsByClassName('bubble-result-container').length`? In my computer, this command returns 2 (one element in the editor pane and another in the watch pane).

**Comment by pierregodard** [comment] 2016-07-22 16:57
this returns `1` as is, but if i add a watch then it returns `2`

**Comment by n-riesco** [comment] 2016-07-22 17:03
Does the watch panel work?
I mean when you type `print("hello")` in the watch, and re-run `Hydrogen: Run` in the text pane, does the watch panel show the result?

**Comment by n-riesco** [comment] 2016-07-22 17:08
Also, it'd help if you could post a screenshot of the console after running `document.getElementsByClassName('bubble-result-container')` and expanding the `<div>` elements it returns.

**Comment by pierregodard** [comment] 2016-07-22 17:10
was just doing that ;) not sure what should be in there but it doesn't look there's anything like a "hello".

<img width="451" alt="screen shot 2016-07-22 at 19 08 14" src="https://cloud.githubusercontent.com/assets/4210161/17064978/c0102ede-503f-11e6-8cf7-e5060799ac9e.png">

**Comment by pierregodard** [comment] 2016-07-22 17:34
and yes the watch panel works:

<img width="604" alt="screen shot 2016-07-22 at 19 33 28" src="https://cloud.githubusercontent.com/assets/4210161/17065646/4c7e96fa-5043-11e6-85e5-bba30c0e115e.png">

**Comment by n-riesco** [comment] 2016-07-22 17:52
In the previous screenshot, did you type a 2 in the watch panel? If so, the first `div` must be in the watch pane, and the empty one must be in the edit pane.

These are the unexpected results I've notice up to this point:

- the watch panel is created on kernel startup (regardless of whether is visible or not). So, I'd expect `document.getElementsByClassName('bubble-result-container').length` to be 2.

- The console log reports `ResultView: Rendering as  <pre>​hello​</pre>​`, but the `div` in the editor pane is empty.

Please, could you repeat the same exercise (after restarting Atom and without the watch panel)?
But this time, please,  run `document.getElementsByClassName('bubble-output-container')` and post the screenshot after expanding the `div`s.

**Comment by pierregodard** [comment] 2016-07-22 18:13
thank you for all your help!

> In the previous screenshot, did you type a 2 in the watch panel? If so, the first div must be in the watch pane, and the empty one must be in the edit pane.

oh i understand, i had been assigning a `2` to a variable to check if the kernel accessed outside of Hydrogen was taking that into account, so that must have persisted.

> the watch panel is created on kernel startup (regardless of whether is visible or not). So, I'd expect document.getElementsByClassName('bubble-result-container').length to be 2.

i confirm that after relaunching Atom the result of this is `1` though, not `2`

> The console log reports `ResultView: Rendering as <pre>​hello​</pre>`​, but the `div` in the editor pane is empty.

yes that is confusing...

running ` document.getElementsByClassName('bubble-output-container')` returns:

<img width="450" alt="screen shot 2016-07-22 at 20 07 40" src="https://cloud.githubusercontent.com/assets/4210161/17066685/73da2f7a-5048-11e6-9980-3c7a82dfe1fc.png">

**Comment by n-riesco** [comment] 2016-07-22 18:29
@pierregodard If you feel like debugging this further, I'd look at [these lines](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/result-view.coffee#L99-L157).

The line that appends the result to the `bubble-result-container` is [this line](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/result-view.coffee#L138).

And things that could go wrong:
- [setting `container`](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/result-view.coffee#L90-L97)
- [setting `htmlElement`](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/result-view.coffee#L105-L132)

**Comment by pierregodard** [comment] 2016-07-22 21:28
ok thank you for the pointers! that may be a long shot for me since my literacy with Atom and [coffee|java]script is close to null but i'll try. thank you again for all your help

**Comment by pierregodard** [comment] 2016-07-22 22:58
@n-riesco apologies in advance for my rather limited abilities here but i'll try to provide some more information. if i add a breakpoint at `container.appendChild htmlElement` i'm able to look into the container and the beginning looks like this:

<img width="337" alt="screen shot 2016-07-23 at 00 49 30" src="https://cloud.githubusercontent.com/assets/4210161/17073254/6e2d4bb2-506f-11e6-9ccb-66508ed81183.png">

with `mimeType` being `"text/plain"`. So apparently the "hello" text is in there.

Then i'm not sure why but the execution after line 
`if @errorContainer.getElementsByTagName('span').length is 0`

jumps to something that looks like more related to communication with the kernel:

<img width="919" alt="screen shot 2016-07-23 at 00 53 03" src="https://cloud.githubusercontent.com/assets/4210161/17073324/12bdf690-5070-11e6-8145-e95aa2668bb8.png">

any advice on how to investigate further?

**Comment by n-riesco** [comment] 2016-07-23 07:24
@pierregodard On the watch panel, if you click on `div.bubble-result-container`,  you'll be shown the location of this `div` in the DOM. Could you post a screenhot?

At this point, we know that the result is appended to `div.bubble-result-container`. Now, we need to find out where `div.bubble-result-container` is. It should be a child of `div.bubble-output-container` in the editor pane. But from the fact that we don't see a result bubble and that `document.getElementsByClassName('bubble-result-container').length` is 1, we suspect there is none in the editor pane.

**Comment by pierregodard** [comment] 2016-07-23 08:22
if i click on `div.bubble-result-container` i get:

<img width="1238" alt="screen shot 2016-07-23 at 10 14 40" src="https://cloud.githubusercontent.com/assets/4210161/17076905/b7b5cbb6-50be-11e6-944f-34779f19ae5e.png">

but except for `div.bubble-result-container` being a child of `div.bubble-output-container`, itself a child of `div.hydrogen.output-bubble`, i don't see much happening which would support your guess that there is no `bubble-result-container` in the editor pane right?

**Comment by n-riesco** [comment] 2016-07-23 08:40
It looks like `div.bubble-output-container` isn't attached to the DOM (which explains `document.getElementsByClassName('bubble-result-container').length` being 1).

This result is suggesting that the problem is somewhere in the [code creating the output bubble](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L143-L154). In particular [these lines](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L143-L154).

Could you check if [this line](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L151) gets ever run?

**Comment by pierregodard** [comment] 2016-07-23 08:43
ok i'll look at this now. 

in the meantime, here is the output of the console when i relaunch Atom and call `Hydrogen: Run` for the first time. It seems to me that it's the business of connecting to the Jupyter kernel but maybe you'll see something suspicious:

<img width="1003" alt="screen shot 2016-07-23 at 10 32 46" src="https://cloud.githubusercontent.com/assets/4210161/17076991/34710786-50c1-11e6-8421-4369988f2d27.png">

other screenshots i posted before correspond to a second call to `Hydrogen: Run` on the same line. i thought the first call was starting a kernel if none was running but maybe i should have mentioned that earlier.

**Comment by pierregodard** [comment] 2016-07-23 08:58
`view = @insertResultBubble row` [here](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L151) gets executed once (if i make proper use of the debugger).

when i step over though, instead of going to the [following line](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L152) `kernel.execute code, (result) ->` it goes to [that one](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L144) : `unless @watchSidebar?` (which is maybe totally normal as i don't understand yet the `@` syntax)

**Comment by n-riesco** [comment] 2016-07-23 09:17
I've also noticed that erratic behaviour in the debugger (since Coffeescript is a transpiled language, I guess that it's hard for the debugger to know where to set a breakpoint) .

I thought the problem could've been caused by `insertResultBubble` not being called. Could you check that? For example, by setting a breakpoint [here](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L184).

**Comment by pierregodard** [comment] 2016-07-23 09:27
`@markerBubbleMap[marker.id] = view` is called once

**Comment by n-riesco** [comment] 2016-07-23 09:45
I don't trust the debugger (I can see the same erratic behaviour you described [here](https://github.com/nteract/hydrogen/issues/326#issuecomment-234708148).

Would you be able to edit `~/.atom/packages/Hydrogen/lib/main.coffee` and add a `console.log 'insertResultBubble:', @markerBubbleMap` above [this line](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L184)?

If you add this line, the console should output a line starting `insertResultBubble:` and listing all the output bubbles.

**Comment by n-riesco** [comment] 2016-07-23 09:59
On second thoughts, let's try something more straight forward. If you're able to edit `~/.atom/packages/Hydrogen/lib/main.coffee`, could you remove [these lines](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L146-L148) and see if this fixes the problem?

**Comment by pierregodard** [comment] 2016-07-23 10:08
for your second to last suggestion, not sure it's the right workflow (i don't know if i'm supposed to instead call `apm develop hydrogen` etc. to do things in a clean way), but i just edited the file directly and from `console.log 'insertResultBubble:', @markerBubbleMap` i got an empty list in the console:

`insertResultBubble: Object {}`

will try your last suggestion now.

**Comment by pierregodard** [comment] 2016-07-23 10:18
commented out the three lines, reloaded Atom, but it doesn't change the behavior. 

[i also commented out the code responsible for writing `ResultView: Rendering as MIME  text/plain` in the console to actually check that my editing was actually taken into account (and it was).]

**Comment by n-riesco** [comment] 2016-07-23 10:24
On 23/07/16 11:08, pierregodard wrote:
> for your second to last suggestion, not sure it's the right workflow (i don't know if i'm supposed to instead call |apm develop hydrogen| etc. to do things in a clean way), but i just edited the file directly and from |console.log 'insertResultBubble:', @markerBubbleMap| i got an empty list in the console:
> 
> |insertResultBubble: Object {}|
> 
> will try your last suggestion now.

Oops! I should've said to add `console.log 'insertResultBubble:', @markerBubbleMap` **below** `@markerBubbleMap[marker.id] = view`?

**Comment by n-riesco** [comment] 2016-07-23 10:31
On 23/07/16 11:18, pierregodard wrote:
> commented out the three lines, reloaded Atom, but it doesn't change the behavior.

This is baffling. To sum up, we've confirmed that:

- `div.bubble-output-container` is not in the DOM

- despite `insertBubbleResult` being invoked

**Comment by pierregodard** [comment] 2016-07-23 10:37
here is (a part of) the output when `console.log 'insertResultBubble:', @markerBubbleMap` is inserted below `@markerBubbleMap[marker.id] = view`. Not sure what would be the best way to give you the whole thing.

<img width="1279" alt="screen shot 2016-07-23 at 12 34 10" src="https://cloud.githubusercontent.com/assets/4210161/17077487/3a712970-50d2-11e6-8120-1dd54c08b223.png">

**Comment by pierregodard** [comment] 2016-07-23 10:41
> This is baffling. To sum up, we've confirmed that: 
- `div.bubble-output-container` is not in the DOM 
- despite `insertBubbleResult` being invoked

that seems correct from my end. (just growing a bit of anxiety that i might miss something very obvious and waste your time)

**Comment by n-riesco** [comment] 2016-07-23 10:53
Your last screenshot is giving us an important clue. If [this line](https://github.com/nteract/hydrogen/blob/5e846e9cdb2e8b85d35ca4f5495f62d53bb2a718/lib/main.coffee#L179-L182) had worked as expected, then `ResultView.element` in the console log should've been `div.hydrogen.output-bubble.atom--block-decoration-59`, but instead it is missing the `atom--block-decoration-*` class.

You said above that you're using Atom 1.8.0. How did you install it? Did you build from source? Or you used the installer at https://atom.io/ ?

**Comment by pierregodard** [comment] 2016-07-23 10:56
i used the installer from [https://atom.io/](https://atom.io/)
should i try building it from source?

**Comment by n-riesco** [comment] 2016-07-23 11:06
@pierregodard I don't want to waste your time. If this issue is urgent to you, then,  yes go for it and build form source. Otherwise, I will go through the commits in the Atom repository and see if anything is changed in the code for block decorations (I'm not going to do this today, though).

**Comment by pierregodard** [comment] 2016-07-23 11:51
@n-riesco after building Atom `1.10.0-dev-3a4e251` the behavior is unfortunately the same :(

looks like the decoration is still absent on my end:

<img width="985" alt="screen shot 2016-07-23 at 13 44 22" src="https://cloud.githubusercontent.com/assets/4210161/17077744/cae7a00c-50db-11e6-8fd6-c25430eacbf2.png">

i'm happy to continue to try to provide more information on this, but this is certainly not an urgent issue for me. thank you very much for already getting that far with me.

**Comment by n-riesco** [comment] 2016-07-23 12:25
I've tested Atom 1.10.0-dev-3a4e251 and again I can't reproduce this issue.

What Atom packages have you got installed?

**Comment by pierregodard** [comment] 2016-07-23 12:55
i have several community packages although i already tried disabling all of them except `hydrogen` and it didn't change the behavior. Should i try *removing* the community packages? (although i hope this wouldn't erase my packages' settings)

here is the list from `apm list`:
```
├── Hydrogen@0.11.0
├── Zen@0.16.4
├── advanced-open-file@0.16.3
├── atom-beautify@0.29.10
├── atom-reveal-file-in-finder@1.1.4
├── atom-terminal@0.8.0
├── autocomplete-python@1.8.2
├── clipboard-plus@0.5.1
├── emacs-plus@0.11.0
├── expose@0.12.1
├── file-icons@1.7.17
├── git-time-machine@1.5.3
├── imdone-atom@1.3.29
├── intentions@1.0.5
├── language-latex@0.6.1
├── language-pfm@0.82.0
├── latex-friend@0.0.11
├── latextools@0.8.1
├── linter@1.11.14
├── linter-python-pep8@0.2.0
├── markdown-preview-plus@2.4.0
├── markdown-writer@2.4.0
├── minimap@4.24.7
├── nvatom@0.11.0
├── open-recent@5.0.0
├── pdf-view@0.50.0
├── pigments@0.31.2
├── project-plus@0.9.0
├── promote-folder-to-project@2.0.1
├── python-debugger@0.1.0
├── python-indent@0.4.3
├── python-tools@0.6.8
├── script@3.8.2
├── spell-check-test@0.77.4
├── tasks@2.6.0
├── theme-switcher@1.1.0
├── todo-show@1.6.0
└── wordcount@2.6.2
```

**Comment by n-riesco** [comment] 2016-07-23 13:18
On 23/07/16 13:55, pierregodard wrote:
> Should i try /removing/ the community packages? (although i hope this wouldn't erase my packages' settings)

Since I'm not using most of those packages, it'll be easier for me to install them one by one.

**Comment by pierregodard** [comment] 2016-07-23 13:20
(could they have an influence even when they are disabled though?)

**Comment by n-riesco** [comment] 2016-07-23 14:31
No luck! I'm unable to reproduce this issue with any of those packages.

**Comment by pierregodard** [comment] 2016-07-23 15:06
thank you for trying this. i'm a bit at loss on how to continue the investigation as i know very little about how packages work in Atom, let alone my also very limited knowledge of the kind of technologies used here.

**Comment by n-riesco** [comment] 2016-07-23 15:26
On 23/07/16 16:06, pierregodard wrote:
> thank you for trying this. i'm a bit at loss on how to continue the investigation as i know very little about how packages work in Atom, let alone my also very limited knowledge of the kind of technologies used here.

On my side, I want to have a look at Atom's code for block decorations and see where things could go wrong.

On your side, I'd try to rule out a configuration problem:
- Atom stores the configuration for its packages in `~/.atom.config.cson`
- or perhaps, by installing atom locally into a new user and see if the problem is still present.

**Comment by pierregodard** [comment] 2016-07-23 15:58
ok, some news here! i installed Atom on a guest user account, then just installed `hydrogen` and it.......works! (and it's very nice!:)
so definitely a configuration problem on my end. since it's not the packages, it must be some init file. apologies in advance if it's been a stupid configuration issue i should have been able to isolate much earlier. will follow up asap.

**Comment by n-riesco** [comment] 2016-07-23 16:13
Glad to hear at least it's working on a clean install.
It'd be good to know which setting is causing this issue.
Could you have a look at `~/.atom/config.cson` in your user (the one that sees this isssue)?
There'll be settings for all your packages. I'm not going to ask you to go through them, but could you have a look at the `core` and `editor` keys and see if anything catches your eye? Mine is pretty basic:

```cson
  core: {}
  editor:
    invisibles: {}
    showIndentGuide: true
    showInvisibles: true
```

**Comment by pierregodard** [comment] 2016-07-23 16:39
the editor part for me read:

  ```
editor:
    fontFamily: "Source Code Pro"
    fontSize: 13
    invisibles: {}
    scrollPastEnd: true
    softWrap: true
    useShadowDOM: false
    zoomFontWhenCtrlScrolling: true
```

the faulty line is `useShadowDOM: false`. Removing it solves the problem!! :-))
i have absolutely no idea how it got there, it doesn't seem like an accessible option from the `settings` page. I'd like to understand how it got there, but in any case, THANK YOU for bearing with me!

**Comment by n-riesco** [comment] 2016-07-23 16:52
@pierregodard If you feel like contributing, you could update our https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md with a new entry advising users against disabling `Use Shadow DOM` under `Settings > Editor`

**Comment by pierregodard** [comment] 2016-07-23 17:00
will gladly do that. just a very stupid question: the simplest (only?) way to do that is to fork your repo and submit a pull request right?

**Comment by n-riesco** [comment] 2016-07-23 17:02
The simplest way is to edit the file directly on github. Go to https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md and click on the icon pencil.

**Comment by pierregodard** [comment] 2016-07-23 17:24
just did that, thank you.

**Comment by n-riesco** [comment] 2016-07-23 17:30
I've opened an issue on Atom's repository. I'm closing the issue here.

**Closed by n-riesco** 2016-07-23 17:30 UTC

**Comment by lgeiger** [comment] 2016-07-24 12:29
Thank you both for debugging this 🎉
