### ISSUE TITLE
Can hydrogen display ouputs in seperate lines?

### ISSUE THREAD

**Issue by BruceChen2017** [nteract/hydrogen#928] opened 2017-07-24 12:37 UTC
```
def f(x):
    return x**2
f(2)
f(3)
```
The default output will be `49` just in single line,which is bad for me.
So how can I display outputs line by line  just like usual jupyter notebook.

**Comment by BruceChen2017** [comment] 2017-07-25 05:36
@rgbkrk   @lgeiger   @BenRussert

**Comment by BenRussert** [comment] 2017-07-25 14:24
I'll have to try reproducing this when I have a chance. You get `49` consistently each time you run this?
 
I always like to offer intermediate solutions while we look into things. In this case I would suggest using [cells](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run-cell) to separate blocks of code similar to jupyter notebooks.

**Comment by BruceChen2017** [comment] 2017-07-25 15:16
Yes(windows 7).But actually I like to put several expression in different lines of one block so that jupyter will display all results line by line. I really hope you can make this functionality work. @BenRussert 
```
# %%
def f(x):
    return x**2
f(2)
f(3)
output is still displayed by `49`
```

**Comment by rgbkrk** [comment] 2017-07-25 15:38
You need to run each separately for separate output or use `print`. `f(2)` is an expression which means that in an interpreter you're only going to see the last expression here.

Can you take a screenshot or otherwise of what you're talking about with regards to jupyter displaying all results line by line?

**Comment by BenRussert** [comment] 2017-07-25 16:24
What I would expect running @BruceChen2017's example either in one cell of a notebook or all at once in hydrogen is: `9`. If the output you see in hydrogen is `49` that would be something to look into.

@BruceChen2017 a way you could separate cells in hydrogen would be like this:

```
def f(x):
    return x**2
f(2)

# %%
f(3)
```

Running each cell you would get `4` then `9`

**Comment by rgbkrk** [comment] 2017-07-25 16:31
Oh derp, now I understand. `4` and `9` are getting concatenated.

**Comment by BruceChen2017** [comment] 2017-07-26 03:44
Sorry to both of you @BenRussert  @rgbkrk .By default,as @BenRussert shows,both jupyter and hydrogen only display the output of the last expression.But there is a way to show all output of different expressions in  
one cell.
```
# excecute two lines in the file
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
```
or   create `~/.ipython/profile_default/ipython_config.py`  and write:
```
c = get_config()
# Run all nodes interactively
c.InteractiveShell.ast_node_interactivity = "all"
```
What  I did is just the latter.  
So as I said before,can you make this work if I use this setting.Of course ,putting expression in separate cells or using `print` for each expression will work,but you have to type more which is very inefficent for me.  
Anyway,that is just my hope you can ignore.

**Comment by BenRussert** [comment] 2017-09-03 21:01
@BruceChen2017 try pressing shift+enter to run and move down. I do this often to force individual output quickly.

I do see what you are saying, but the challenge is to keep everything language agnostic and to follow the way each kernel provides output for a given block of code.

**Comment by BenRussert** [comment] 2017-10-25 03:02
Closing, since I think we covered the discussion. Thanks for the feedback!

**Closed by BenRussert** 2017-10-25 03:02 UTC
