### ISSUE TITLE
Uncaught Error: dlopen($ATOM_HOME/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node, 1...

### ISSUE THREAD

**Issue by yanceyy** [nteract/hydrogen#639] opened 2017-03-17 02:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.6.0

### Stack Trace

Uncaught Error: dlopen(/Users/wangyang/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node, 1): no suitable image found.  Did find:
	/Users/wangyang/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node: truncated mach-o error: segment __TEXT extends to 1024000 which is past end of file 481016

```
At ELECTRON_ASAR.js:168

Error: dlopen(/Users/wangyang/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node, 1): no suitable image found.  Did find:
	/Users/wangyang/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node: truncated mach-o error: segment __TEXT extends to 1024000 which is past end of file 481016
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.6 
atom-material-ui 1.3.9 
atom-python-virtualenv 0.6.0 
autocomplete-python 1.8.60 
Hydrogen 1.6.0 
script 3.14.1 
term 0.2.4 
```

**Comment by lgeiger** [comment] 2017-03-17 04:00
Puh that's a nasty error 😄 

Could you try reinstalling hydrogen:
```bash
apm uninstall hydrogen
apm install hydrogen
```

**Comment by yanceyy** [comment] 2017-03-17 10:39
Thanks for your reply. i have tried the method you mentioned, but it does not work on my computer. i still received the same Uncaught Error after i installed it.😭

**Comment by lgeiger** [comment] 2017-03-17 11:24
Do you receive any errors during the install with `apm install hydrogen`?

Could you try running `apm rebuild hydrogen`? This will rebuild our native dependencies against the correct Electron headers.

**Comment by lgeiger** [comment] 2017-03-17 11:33
If that doesn't help we should try one more time to reinstall Hydrogen. For this:
1. Close Atom
2. Run `apm uninstall hydrogen`
3. Run `rm -rf /Users/wangyang/.atom/packages/Hydrogen/` just to make sure 😄 
4. Run `apm install hydrogen`

**Comment by yanceyy** [comment] 2017-03-17 13:53
thanks for your help. i do not receive any error during installing hydrogen.
➜  ~ `apm install hydrogen`
`Installing hydrogen to /Users/wangyang/.atom/packages ✓`

and  `apm rebuild hydrogen` seems do not work. when i use '`hydrogen: run` ' in Atom, it  will pop up the same error as before. and the 4 steps reinstallation also does not work.

These methods can not fix the problem, maybe i have installed some incompatible packages by pip in the past. i will reinstall my computer operating system to try in the future. 

All in all thanks for your help.

**Comment by lgeiger** [comment] 2017-03-17 14:33
I'm sorry I have no idea how to fix this.
It's strange I'm running Atom 1.15.0 on macOS 10.12.3 without any problems.

**Comment by frivollier** [comment] 2017-06-18 04:48
I have the exact same problem:
<img width="528" alt="screenshot 2017-06-18 00 28 12" src="https://user-images.githubusercontent.com/1471806/27258045-2ce85c6c-53bd-11e7-8bb1-0432169fb70b.png">

the kernel runs for 30 seconds, I am able to execute a few commands, then is crashes.
I need to restart to get it back and running
I have tried to reinstall many times without success. 
- Python 3.6 via anaconda distrib
- Atom 1.18
- Hydrogen 1.17.1

Any help will be appreciated

![hydrogen error](https://user-images.githubusercontent.com/1471806/27258127-c1192a0e-53bf-11e7-82f6-3ab9d8a8c1e6.gif)

**Comment by lgeiger** [comment] 2017-10-15 19:27
@frivollier This error is thrown from your python process and not from Hydrogen itself. It looks like your Python installation is corrupted.

**Comment by frivollier** [comment] 2017-10-16 04:01
Thanks for the feedback, I tested  Hydrogen on another mac machine where it
actually runs fine. They both have slightly different python environments
so I will try to figure out what’s wrong and report.

Frederic


On October 15, 2017 at 3:27:29 PM, Lukas Geiger (notifications@github.com)
wrote:

@frivollier <https://github.com/frivollier> This error is thrown from your
python process and not from Hydrogen itself. It looks like your Python
installation is corrupted.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nteract/hydrogen/issues/639#issuecomment-336735090>,
or mute
the thread

**Comment by frivollier** [comment] 2017-10-17 03:24
@lgeiger I am unable to get rid of this error. I have tried many things unsuccessfully.  
Any recommendation to troubleshoot will be appreciated.

**Comment by BenRussert** [comment] 2017-12-07 20:00
@frivollier Do you get the same issue when using hydrogen with any code you run, or just when using the `SolarGISwebapi` package and `getSolarGIS` function from your gif?

**Comment by frivollier** [comment] 2017-12-07 20:18
I get this error with any libraries or code file. 

I was able to get it to run without crashing with Atom in developer mode but it is not consistent

**Comment by wadethestealth** [comment] 2019-07-25 01:15
Closing as the issue is old and there have been many updates to both hydrogen and atom

**Closed by wadethestealth** 2019-07-25 01:15 UTC
Labels: install, mac
