### ISSUE TITLE
I installed jupyter kernel but it is showing null grammer exception

### ISSUE THREAD

**Issue by LokeshhCB** [nteract/hydrogen#1709] opened 2019-07-13 07:46 UTC
### Prerequisites

* [ ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

[Description of the bug]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

OS version:
[Your OS's version]

> `atom --version`

```

```

> `apm --version`

```

```

Hydrogen version:

[Your Hydrogen's version]

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]

### Expected behavior

[A clear and concise description of what you expected to happen.]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by aviatesk** [comment] 2019-07-13 07:58
Unless you provide us the detail of your issue, I gonna close this ...

**Closed by aviatesk** 2019-07-13 07:58 UTC
Labels: bug :bug:

**Comment by wadethestealth** [comment] 2019-07-13 14:06
This is a duplicate of many other issues, but they all seem to talk about multiple topics. Anyways, the way to fix your issue is to use hydrogen inside a file with the correct grammar for instance a .py file for python. Here you are using a random untitled file and it has no grammar.
