### ISSUE TITLE
Execution doesn't resolve unless the file is saved

### ISSUE THREAD

**Issue by willwhitney** [nteract/hydrogen#53] opened 2015-06-08 18:00 UTC
https://github.com/willwhitney/hydrogen/issues/52

**Comment by willwhitney** [comment] 2015-06-15 20:26
I can't reproduce this — can anyone give me concrete steps?

**Comment by n-riesco** [comment] 2015-06-15 21:11
I've just checked on a machine with:
   IPython 3.0.0
   Atom 0.207.0-2337254

and followed the steps:
- Open Atom (no tabs)
- Open a Python file, test.py, that contains:
  print "Hello, Jupyter!"
- Position the cursor at the end of the line and press ctrl-alt-enter
- The spinner doesn't stop
- Open a Javascript file, test.js, that contains:
  console.log("Hello, Jupyter!");
- Position the cursor at the end of the line and press ctrl-alt-enter
- The spinner doesn't stop
- Click on the tab for test.py and now it shows
  Hello, Jupyter!
- Click on the tab for test.js
- Press ctrl-s, and the spinner stops and shows:
  Hello, Jupyter!
   undefine

**Comment by willwhitney** [comment] 2015-06-15 22:11
OK, this definitely doesn't repro on Mac. Can I get you to help track down what's going on?

Here are the logs I see when I follow the steps through running the Python code:

![screenshot 2015-06-15 18 10 34](https://cloud.githubusercontent.com/assets/597829/8171926/ddff4ffe-1389-11e5-95b7-46f0ff764bd1.png)

What looks different?

**Comment by n-riesco** [comment] 2015-06-16 08:18
I get some syntax errors in kernel-manager.coffee (I'm using v0.4.0).

**Comment by willwhitney** [comment] 2015-07-02 19:37
Sorry, lost track of this issue. The line causing the error looks like it must be:

```coffeescript
languageMappings = JSON.parse atom.config.get('Hydrogen.languageMappings')
```

What do you have in the the "language mappings" field in the settings?

**Comment by n-riesco** [comment] 2015-07-02 20:07
This is what I get in the console, before pressing ctrl-alt-enter:

> atom.config.get("Hydrogen.languageMappings")
<- undefined

after pressing ctrl-alt-enter:
> atom.config.get("Hydrogen.languageMappings")
<- "{}"

**Comment by willwhitney** [comment] 2015-07-02 20:37
I think Atom must have a race condition with getting that set (maybe just on some platforms?).

I'm already doing a check for that, but I'll be a little more careful about it. I'm not sure this is the issue, but we can see if it helps.

**Comment by n-riesco** [comment] 2015-07-02 20:41
I'm not running the latest atom. I will update and let you know (although not today).

**Comment by willwhitney** [comment] 2015-07-02 20:46
Cool, no worries. Thanks for the help!

**Comment by n-riesco** [comment] 2015-08-29 07:31
Finally, I got around testing this issue again. I followed the steps described [here](https://github.com/willwhitney/hydrogen/issues/53#issuecomment-112213298); this time using the latest versions:
- atom v1.0.8
- hydrogen v0.4.4
- jupyter v4.0.4
- ipython v4.0.0
- ijavascript v5.0.5

The problem is still present, but I've also noticed that the execution also resolves:
- if I switch tabs
- or if the folder panel gets updated (e.g. by creating a file using the command line).

I would like to help debug this issue, but I'm not familiar with `atom`. How do you usually go about debugging issues in `hydrogen`?

**Comment by n-riesco** [comment] 2015-08-29 13:50
OK, this is how far I've got at the moment:
1. Hydrogen launches the kernel
2. Hydrogen invokes kernel.execute
3. I've confirmed that, at this point, the kernel process:
    - is running
    - receives the execute_request
    - and sends back the expected replies
4. Despite the kernel having already replied, none of the socket listeners set up by Hydrogen gets invoked.

I don't understand the reason, but it's like if the V8 event loop was paused. The event loop starts working as usual:
- if I save the file,
- or if I switch to another tab and then switch back
- or if I run `setImmediate(function{})` in the Javascript console.

**Comment by essicolo** [comment] 2016-12-06 21:22
Hydrogen works fine with Python, but the spinner lasts forever with R. I'm on Windows 10 with Atom 1.12.6. I have installed version 0.7 of the IRkernel with conda. I have added R to the system path, but I'm not familiar with this. Maybe I did it wrong:

C:\Program Files\R\R-3.3.2\bin\x64

No error message in Atom. Just Hydrogen telling me on start that the Python and R kernels were updated.

**Comment by n-riesco** [comment] 2016-12-29 10:25
@essicolo Since the issue is only with the R kernel, please could you open a new issue? Also could you include a screenshot of the log messages in the dev console (shift-ctrl-i) when the spinner appears?

**Comment by n-riesco** [comment] 2016-12-29 10:40
I'm closing this issue, since it hasn't been seen recently and the last last time that was seen we were using the old `zmq`.

**Closed by n-riesco** 2016-12-29 10:40 UTC
