### ISSUE TITLE
Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /opt/atom/resources/app/static/pdf...

### ISSUE THREAD

**Issue by kumazawajiro** [nteract/hydrogen#846] opened 2017-06-02 09:13 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.15.0

### Stack Trace

Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /opt/atom/resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'

```
At /home/yuto/.atom/packages/Hydrogen/node_modules/requirejs/bin/r.js:2607

Error: Tried loading "pdfjs-dist/build/pdf.worker" at /opt/atom/resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1946:33)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1133:51)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1935:21)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1084:29)
    at Object.fetch (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1074:66)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1106:30)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1807:39)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1411:33)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:384:23
    at each (/packages/Hydrogen/node_modules/requirejs/bin/r.js:309:31)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1363:17)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1710:36
```

### Commands

```
     -0:15.2.0 export-html:export (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-html-preview 0.1.22 
atom-pronama-chan 1.0.1 
atomic-chrome 0.3.0 
auto-encoding 0.7.0 
autoclose-html 0.23.0 
autocomplete-clang 0.11.3 
autocomplete-haskell 0.7.2 
autocomplete-paths 1.0.5 
busy-signal 1.4.1 
color-picker 2.2.5 
docblockr 0.10.3 
editor-stats 0.17.0 
editorconfig 2.2.2 
export-html 3.1.0 
file-icons 2.1.7 
git-history 3.3.0 
haskell-ghc-mod 1.19.9 
hey-pane 1.0.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 1.15.0 
ide-haskell 1.9.6 
intentions 1.1.2 
language-gnuplot-atom 0.2.0 
language-haskell 1.12.1 
language-latex 1.0.0 
language-restructuredtext 1.1.0 
language-source-cfg 0.3.1 
latex 0.43.0 
latexer 0.3.0 
latextools 0.8.5 
linter 2.1.4 
linter-clang 4.1.1 
linter-csslint 1.3.4 
linter-hlint 1.0.1 
linter-htmlhint 1.3.3 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.0 
linter-write-good 0.9.0 
local-history 4.3.0 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-recent 5.0.0 
pdf-view 0.58.0 
pigments 0.39.1 
project-manager 3.3.5 
quick-highlight 0.10.0 
regex-railroad-diagram 0.17.0 
rst-preview-pandoc 0.1.12 
save-session 0.15.7 
script 3.15.0 
scroll-through-time 0.2.0 
show-ideographic-space 1.0.2 
sort-lines 0.14.0 
split-diff 1.4.0 
symbols-tree-view 0.14.0 
tablr 1.8.3 
term3 0.22.1 
toggler 0.3.0 
trailing-spaces 0.4.0 
web-search 0.3.3 
web-view 3.0.0 
```

**Comment by lgeiger** [comment] 2017-06-02 10:08
Duplicate of #777

**Closed by lgeiger** 2017-06-02 10:08 UTC
